### ISSUE TITLE
Webman stops working after restarts / config file corrupted?

### ISSUE THREAD

**Issue by Hybrid-Divide** [aldostools/webMAN-MOD#1006]
Currently running: WebMAN-Mod v 1.47.45 (Full version)
Firmware: [CFW Evilnat 4.90 Cobra 8.4 [PEX] [CEX]] (md5 hash checked out fine)

Swapped my PS3 from an HDD to an SSD.  Seemed to work fine before, but now after install, WebManMOD won't work without a hard reboot, sometimes also requiring the Webman config file to be deleted.
THEN it'll work, and while I have it on, Webman will work fine.
But if I change a setting, like manually setting fans to 35%, once I save and hard reboot, it's not working again.
Again, requiring a hard reboot. Sometimes that works, other times, the config file also needs to be deleted again.

When it isn't working, I go to the setup page, and get the following error:
The page cannot be displayed. (8071053d).

Cobra is enabled, and the internet connection works.

I have completely reset the system multiple times, even reformatting the SSD, requiring the Evilnat CFW to be installed again.
Uninstalled and reinstalled Webman multiple times, even got the installer from here on github.

Could it be that I'm on the [PEX] [CEX] build?  
I wouldn't think that has anything to do with it, considering that I was running it before the HDD/SSD swap without issues.
I wouldn't think it's the SSD, either.  That seems to be working fine, and is brand new. (Crucial MX500 1TB)

All assistance appreciated.

**Comment by aldostools** [comment]
8071053d = Server timeout = That means that webMAN MOD plugin isn't running. Therefore the web server is not responding.

I recommend that start removing webMAN MOD manually:
https://github.com/aldostools/webMAN-MOD/wiki/~-Uninstalling-webMAN-MOD

Then install webMAN MOD using the latest package from https://github.com/aldostools/webMAN-MOD/releases

Also you could consider installing [CEX] instead of [PEX] to discard any potential issue in the CFW.

If the problem still persists, it is possible the your SSD could have some compatibility issues with your PS3. In that case it would be recommended to revert to your previous HDD or install a new mechanical HDD or hybrid HDD (SSHD).

SSD issues are very common due the technology is too new for the PS3. Here is a guide that mention some incompatibilies:
https://www.psx-place.com/threads/guide-ssd-for-playstation-3.42499/

**Comment by Hybrid-Divide** [comment]
I'll look into it and report back.  Thank you.

**Comment by Hybrid-Divide** [comment]
I think I figured out the real problem.  I had a USB drive plugged in!
I saw you mention in a forum post somewhere to remove USB drives, so I tried that and it worked!

Don't recall that being a problem before, but for all I can remember, I had taken them out previously!
But so far, so good.
I'll go ahead and close this out.  Thanks again for your hard work!
