### ISSUE TITLE
Ylod while using webman

### ISSUE THREAD

**Issue by Littlegish** [aldostools/webMAN-MOD#1019]
I encountered a problem that when I turn on temperature monitoring and start using the menus in evilnat, the console may fall into ylod with errors: 1701 and immediately 1601
the console works fine, I tried installing different versions of webman: lite, full & normal and the behavior was the same everywhere
This only happens on fat consoles, I haven’t seen this on slim consoles

more than 5 consoles were tested from CechG to CechL models

**Comment by aldostools** [comment]
I suggest that enable debug version of Cobra and run socat to capture the system messages when the system crashes.
The debug log could show some information that may help to indeify the cause.

Another test to perform is to install Rebug Lite 4.86 or Rebug REX 4.84 and check if you have the same behavior.
If you don't get the Ylod on these CFW, then the issue could be related to Evilnat CFW.

You don't specify if you're using Evilnat 4.90 PEX or CEX. if you're using PEX edition, you could try CEX version.
PEX edition is an hybrid of 4.84 and 4.90. Although it has been tested extensively, it's possible that some rare issue could exist.

EDIT:
If the PS3 console is using an SSD disk as internal storage, the issue could be related to that since SSD is known to cause various issues.

**Comment by Littlegish** [comment]
> I suggest that enable debug version of Cobra and run socat to capture the system messages when the system crashes. The debug log could show some information that may help to indeify the cause.
> 
> Another test to perform is to install Rebug Lite 4.86 or Rebug REX 4.84 and check if you have the same behavior. If you don't get the Ylod on these CFW, then the issue could be related to Evilnat CFW.
> 
> You don't specify if you're using Evilnat 4.90 PEX or CEX. if you're using PEX edition, you could try CEX version. PEX edition is an hybrid of 4.84 and 4.90. Although it has been tested extensively, it's possible that some rare issue could exist.
> 
> EDIT: If the PS3 console is using an SSD disk as internal storage, the issue could be related to that since SSD is known to cause various issues.

im using CEX cfw 4.90 with internal hdd (100% working) 
How to enable debug log? I'll try to recreate the crash
where can I find the log after the crash?
if the log doesn’t show anything useful then I’ll try to downgrade it to rebug as you suggested
