### ISSUE TITLE
XMB freeze & External ntfs iso black screen

### ISSUE THREAD

**Issue by Turbosain** [aldostools/webMAN-MOD#1054]
Hello Aldo, 
I hope you are doing great 
Many thanks for your great work .

Am facing several problems since I updated to HFW 4.91 and hen 3.3.0 

Webman 1.47.46 & 1.47.45 

XMB freezes when I run webman commands such as Uninstall or block psn servers.

Sometimes it will freeze just by entering webman options .

The only way to unfreeze is by hard power off and on again and wait till system file corruption check .

Other major problem for me is I run my ISO games via external drive 

Everything was working smoothly without any problems on HFW 4.90 and webman 1.47.45 .
I prep ntfs and the games show,mount,run with no problems .

The problems only happened on the latest HFW & hen 

Things I tried : 
Using lite and full install of both 1.47.45 & 1.47.46

Reinstall HFW twice via xmb or safe mode 
Along with reinstalling hen via auto installer .

Delete /dev_hdd0/tmp/wm_config.bin 

Uninstalled other homebrew apps to avoid conflicts if there are any.

Same problem happens with all ISOs mounted via webman . 

((This problem happened in two slim CH300.. consoles)) and the fixes I tried were done on both consoles . 

The only fix I found is by uninstalling webman Reinstall HFW & hen and use irisman to mount and run games .

Most of the games will run just fine without webman present in the system. 

A game that didn't even work with all those fixes is COD black ops II . It was working on the previous HFW 4.90 and previous hen . But now it won't work with any of the said apps . But other ISOs do .

Thank you in advance .

**Comment by aldostools** [comment]
Many black screens on games like COD Black Ops II generally are solved converting the game to ISO.

The current PS3HEN is known to have issues with mappings. I'm not aware about other issues since the kernel & vsh in 4.91 are the same from 4.89. You could try installing that payload.

Some users have reported success using the unofficial "RUS" PS3HEN for 4.91. You could try this version if you prefer.
[nikolaevich23.github.io](https://nikolaevich23.github.io)

Additionally you can try any previous version of webMAN MOD. I had users reporting that 1.47.38 was working better for them.
You could try installing 1.47.44 or 1.47.45 which was working fine on your system.

It's highly recommended that you restart and run prepISO again if you used multiMAN or IRISMAN. These backup managers apply memory patches and update the cache files for external games. That could cause issues in webMAN MOD.

**Comment by Turbosain** [comment]
Hello again, Aldo,  and thank you for your kind response .

I can confirm that Webman 1.47.38 full version is working smoothly with HEN 3.3.0 and HFW 4.91 .

Actually, I don't know the reason, but this release is so much smoother than 1.47.46.
No XMB lagging nor freezing , games mount and dismount seemesly ,commands are running without any problems . 


Also worth mentioning that the problem with COD black ops ii wasn't related to Webman nor HEN , the game had a problem with consoles logged in PSN account during launch no matter OFW,HFW or CFW and no matter if the game was PKG,ISO or JB.
The fix was to log out of PSN before launching the game .


Thanks again, Aldo, for your great work. 
Wish you the best of luck.
