### ISSUE TITLE
CFW Tools MOD causing QA Toggle to not work

### ISSUE THREAD

**Issue by therevtanker2100** [aldostools/webMAN-MOD#1106]
Dunno if anyone else experienced it and got it fixed but I'm having this issue where I can't enable the QA Flags the text went missing before too on that section.

**Comment by aldostools** [comment]
Thanks for the bug report. The QA menu was still using the menu from early betas. It's now fixed with QA menu from BETA 10.

Use webMAN MOD online updater to download the latest build or use this link from Resources - MODS - Releases
https://github.com/aldostools/Resources/releases/download/MODS/4.91.2_Evilnat_Custom_Firmware_Tools_MOD_req_dev_blind_enabled.pkg
