### ISSUE TITLE
Mounts PKG folder twice making the user have to manually install

### ISSUE THREAD

**Issue by therevtanker2100** [aldostools/webMAN-MOD#1107]
While trying out what you mentioned on Twitter turns out my legit PKGs were being mounted twice causing an error during installation.

**Comment by aldostools** [comment]
Please explain better. Add screenshots if possible. The PKG is a modified version of multiMAN 4.84.00 found in Brewology.

It mainly changes the path /dev_hdd0/tmp/wmtmp to /dev_hdd0/tmp/mmtmp
It also updates old Help links and display 4.91 instead of 4.75

prepNTFS.self was replaced with a new version based in prepISO for exFAT & NTFS support 

So I don't see any relation of the changes with your issue.

**Comment by therevtanker2100** [comment]
ok gimme a minute
