### ISSUE TITLE
PS1 Emu

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#1133]
Aldo, something seems off.

I'm mounting PS1 games, and the notification says ps1_emu.self is loaded. However, it looks like ps1_netemu is actually being loaded. I replaced my ps1_netemu with Kozarov's modded version, so the widescreen patch is applied, but my ps1_emu.self is untouched.

Also, ps1_netemu.self is not checked in my WebMAN settings.

**Comment by aldostools** [comment]
Hello @LuanTeles,
Thank you for your feedback. webMAN MOD has 3 options to select the default PS1 emulator:
- ps1_netemu check box option in /setup.ps3
- pressing shoulder buttons when the game is being mounted: R2 = ps1_netemu, L2 = ps1_emu, R1 = switch current emu
- If the tag `[netemu] ` is found the file name, ps1_netemu is used

However as the notification says ps1_emu.self was loaded, I discard that webMAN MOD is using any of these options.

If I remember correctly, the PS3 also auto-selects the emulator based on title id or game format (PKG or disc).

As you're testing on a PS3 system heavily modified, I would suggest you do the following:
- test if the issue still happens with webMAN MOD uninstalled, mounting the PS1 games with mmCM
- test removing all fw mods by reinstalling the firmware (this is to confirm that the issue is not caused by the mods)

**Comment by LuanTeles** [comment]
Hey Aldo,

I performed a fresh install of EvilNat 4.91 Beta 10, deleted webMAN MOD, and then reinstalled it from scratch. I also installed @kozarovv's `ps1_netemu.self` with the widescreen patches.

Here’s the mounted game:
![image](https://github.com/user-attachments/assets/cb213d58-1c67-462e-87df-6e9b03e18c2d)

Proof that I only replaced the `ps1_netemu.self`:
![image](https://github.com/user-attachments/assets/5bffe7d4-2f57-46f3-84a6-57d64100e4ce)

Here's the game running:

Note that the widescreen patch is applied via the emulator. Check out the NEW YORK sign, without the patch, it would only display “W York” on the screen.
![image](https://github.com/user-attachments/assets/1dfd9647-00e6-487b-9e52-982be3f1e4f0) 

Here's without the ps1_netemu.self patch

![image](https://github.com/user-attachments/assets/8b8603c3-ae9b-4217-a80f-a76ed6a5ed22)

**Comment by LuanTeles** [comment]
Interesting that mounting the game via multiMAN still has the ps1_netemu patch applied.

Maybe is it a cobra issue?

**Comment by aldostools** [comment]
Hello LuanTeles,
I was going to ask you if you tested that.

If I recall correctly, basic_plugins.sprx decides which PS1 emulator should be used based on the title id.

If you mount the game with R1 pressed, webMAN MOD will swap the emulators. So if basic_plugins.sprx decides to use ps1_netemu, as the paths of the emulators are swapped in memory, it should use ps1_emu.self

**Comment by aldostools** [comment]
Early Cobra payload by Rebug Team had a patch to force use ps1_netemu instead of ps1_emu.
https://github.com/aldostools/COBRA/blob/master/446/SRC/stage2/modulespatch.c#L122-L126

But as the patch was commented out and it was not being applied, the code for that module was completely removed from modulespatch.c and modulespatch.h in later versions of Cobra.
![image](https://github.com/user-attachments/assets/080e267d-5b2b-4717-a5d5-ac3e17e35e75)

Months later, in webMAN MOD I re-introduced the feature using a different approach to select the ps1 emulator swapping the paths with the map path syscall.

**Comment by Goatman13** [comment]
Spiderman is forced to run in ps1_netemu by internal ps1_emu list. Doesn't matter how you launch it, it will always end up in ps1_netemu.

**Comment by aldostools** [comment]
You can try remapping both ps1 emulators (ps1_emu and ps1_netemu) to `///dev_flash/ps1emu/ps1_emu.self`

`0/remap.ps3/dev_flash/ps1emu/ps1_netemu.self&to=///dev_flash/ps1emu/ps1_emu.self`
`0/remap.ps3/dev_flash/ps1emu/ps1_emu.self&to=///dev_flash/ps1emu/ps1_emu.self`

Or physically replace ps1_netemu.self with ps1_emu.self (BUT I do NOT recommend to do this)
