### ISSUE TITLE
ISO decryption key files on NTFS do not work without running PrepISO

### ISSUE THREAD

**Issue by admiralspeedy** [aldostools/webMAN-MOD#1144]
I'm not sure if this is intended behaviour, but it appears that with the integrated prepNTFS, encrypted ISOs are not usable because their key files are not copied to the temp folder.

For them to work, I have to manually run prepISO after adding a new game. Why?

**Comment by aldostools** [comment]
prepISO is the recommended way to scan the NTFS, exFAT and ext2/3/4 external drives.

The internal prepNTFS is limited in many ways, including that it doesn't has implemented the support for encrypted ISOs.

**Comment by admiralspeedy** [comment]
I see, well unfortunately prepISO seems incredibly unreliable and every second or third time I scan after adding new games it just freezes my console on a black screen (which I see reported on forums as pretty common thing) and I have to force shutdown my console, which then means I have to do the dumb file system check when I turn it back on.

I think the lack of encrypted ISO support should be mentioned somewhere in the documentation (and if it is already, I cannot find it).

**Comment by aldostools** [comment]
Try disabling the internal prepNTFS in webMAN MOD, then scan with prepISO a moment after reboot.

The NTFS driver can become unstable after a few connections/disconnections from homebrews that use the library.

**Comment by admiralspeedy** [comment]
Interesting, will try.

Can I ask why it's not possible to just integrate the complete prepISO directly into webMAN MOD instead of using the lesser prepNTFS?

**Comment by admiralspeedy** [comment]
Where do I disable the internal prepNTFS? I can't seem to find it.

**Comment by aldostools** [comment]
Some reasons are:
1- The NTFS library in webMAN MOD is a stripped version of the NTFS library used in prepISO. This is due memory limitations in the VSH plugins that run on XMB, whil prepISO uses the app memory container. 
2- ntfslib_prx was ported to PS3 SDK, while the original ntfslib_ext uses PSL1GHT SDK. This results in differences between both libs.
3- The exFAT library is available for PSL1GHT SDK only (the same SDK of prepISO). The VSH plugins require PS3 SDK.
4- Due the limited memory available in VSH, other features in prepISO are not available in prepNTFS like support for FakeISO or extract PNG images from the ISO.


> Where do I disable the internal prepNTFS? I can't seem to find it.

In /setup.ps3 uncheck /dev_ntfs
![image](https://github.com/user-attachments/assets/d962a63c-47d5-4c34-bb70-4155cbca4eef)

**Comment by admiralspeedy** [comment]
Speaking of extracting PNG images from ISOs, is it not possible to display ICON0 with the correct aspect ratio at all? Right now if you choose to use ICON0, they are compressed to the wrong aspect ratio and look dumb, but maybe that's a limitation of the XMB?

**Comment by aldostools** [comment]
The issue with the aspect ratio is due ICON0 uses a wide rectangle, while the links generated by webMAN use squared images.

For a proper aspect ratio it's required to add transparency and image manipulation to generate squared images that show correctly on XMB. This gets more complex because other ISO formats like PS1, PS2 and PSP use different aspect ratios too.

All this is documented in the wiki
https://github.com/aldostools/webMAN-MOD/wiki/Game-Paths-&-Covers#covers

**Comment by admiralspeedy** [comment]
I did read that, but I don't understand why the icon sizes can not be just set correct? Obviously the XMB supports those wide icons because they are displayed when a disc is loaded/ISO is mounted in the games list, or by installed PKG games.

**Comment by aldostools** [comment]
Of course ICON0.PNG are supported on XMB applications, but webMAN MOD uses XMB web links to work.
The XMB sends a http request with the selected game to webMAN's web server and the path indicated in the URL is mounted.

Unlike the XMB applications, the XMB web links use a squared icon.

If an ICON0 is used, the icon overlaps the text and looks really ugly. 

PS1 and PS3 covers have a semi-squared aspect ratio, but ICON0 looks horrendous when they are stretched.
That's why it's recommended to use the covers packs.

**Comment by admiralspeedy** [comment]
Ahh, that makes sense.

I'll close this now since it is off topic and you already answered my original question. Thanks!
