### ISSUE TITLE
Occasional ISO Mount Failure via ps3netserv

### ISSUE THREAD

**Issue by EzDzzIt** [aldostools/webMAN-MOD#1164]
Hi, thanks for everything you've done with these tools! Was wondering if there were any recommendations for an issue I'm seeing. 

I am loading games via webman-mod and ps3netserv (share was automatically configured via retronas). Using latest evilnat cfw and latest webman-mod. Retronas is running on a pi4 with a connected hdd. 

The share definitely seems to be working. I see shared isos listed on the web server and in the xmb games folder. The issue I'm hitting is that when attempting to mount isos via the share, that mounting process _occasionally_ fails. It's not really consistent which isos work/don't; for example, mounting demons souls will show the "corrupt data" disc icon; I'll unmount and remount a couple times, then it will work. Or sometimes it will work on the first shot, but another game won't and will appear like corrupt data. Once mounted, I can get in game, and gameplay seems unaffected. 

Thanks!

**Comment by aldostools** [comment]
Hello @EzDzzIt 
Thank you for your comments. There are some possible causes for your issue:

1- If you mount games through Wireless, there are many factors that can result in an inconsistent connection: interference, traffic, walls, signal, speed, configuration, etc. You have 3 possible scenarios: PS3 using Wifi, NAS using Wifi or both. For ps3netsrv the recommended setup is using Ethernet LAN connection.
2- The number of files in the ISO is another factor. Games with many files may take more time to mount on XMB and there could be a timeout while it happens. Test with smaller ISOs to check if the issue is related to this cause.
3- Background processes running on XMB or on your pi4; and memory usage also can cause inconsistent results. Try disabling other plugins and verify that there is enough free memory. If you have a PC, check if you get the same issues.
4- Version of webMAN MOD or ps3netsrv could be part of the issue. Try using the latest versions. If you already have them, try older versions to check if it's caused by a bug in that particular build. Also try with multiMAN.
5- Verify that the ISO is not corrupted copying the game locally to PS3 or checking the ISO with IRD.

**Comment by EzDzzIt** [comment]
Thanks for the note! Based on testing, I think it may be timing out like you said. I'll see what I can do to adjust.
