### ISSUE TITLE
Micro slow down issues with the last update with ps2 games (CECHC04)

### ISSUE THREAD

**Issue by R3g1IT** [aldostools/webMAN-MOD#1165]
I updated with the 1.47.i and now I manifest this problem while playing ps2 games. The previous version doesn't had this problem.

**Comment by aldostools** [comment]
If you install the previous version, does it work fine again? If so, which version to compare?

AFAIK The latest build doesn't have changes related to PS2 games, except for the addition of new CONFIG files that are used only if the PS2 ISO doesn't have already a .CONFIG file associated.

**Comment by R3g1IT** [comment]
Now I try the older version, the last version that work well for me was the 1.47h. Thanks for the reply.

**Comment by aldostools** [comment]
Could you re-install the latest version again just to confirm that the issue returns installing 1.47.47i?

If the issue re-appears, then it's a weird issue because webMAN MOD is not even loaded while PS2 games are emulated.
webMAN MOD basically mounts the game and the PS2 emulation is done by ps2_gxemu in your case.

Also you can check if the issue also happens if you enable ps2_netemu in /setup.ps3

**Comment by R3g1IT** [comment]
I reinstalled the 1.47h and now the issue not present, yes I confirm that I was using ps2gx_emu  not netemu in both cases.

**Comment by R3g1IT** [comment]
I try with netemu but in this case my game was really bad (WRC 3 ps2)

**Comment by aldostools** [comment]
And if you re-install 1.47.47i with ps2_gxemu?

**Comment by R3g1IT** [comment]
I reinstalled the 1.47i, now the issue seems to been solved
