### ISSUE TITLE
Video rec streaming

### ISSUE THREAD

**Issue by Nomeji** [aldostools/webMAN-MOD#12]
Here's a feature request!
The video rec feature is actually barely working. Games always freeze when recording start.
I have a idea or more like a work ground to improve this feature.
Instead of writing video to PS3 HDD we could stream the video on a udp socket. We could next receive the stream using something like ffmpeg/OBS (or/and netcat) on a computer to encode and record the video.
This could help:
- Reading, writing problem
- Reduce CPU usage by sending video and audio stream as raw or uncompressed format
- Possibility to make livestreams (Twitch)

I don't know if it's actually possible but as I said, it's just a work ground.
Here is how to stream using ffmpeg : https://trac.ffmpeg.org/wiki/StreamingGuide
Something similar is used on 3DS CFW : https://gbatemp.net/threads/tutorial-3ds-screen-recording-without-a-capture-card-ntr-cfw-method.423445/

**Comment by aldostools** [comment]
Thank you for your comments. The idea is good, although I don't think I'm able to implement it.

The video rec is more an exploit than a feature. It's something that we're not supposed to be doing in many games. The freeze is mainly related to the _limited memory_ available than due to latency in the recording to HDD.

Additionally, the video recording is done using the APIs already available in VSH. So it's a black box that I cannot modify.

For video recording, it is suggested to load only the standalone video_rec plugin, without loading any other plugin that could use extra memory.

**Comment by Nomeji** [comment]
Okay,
I wasn't aware that video rec was a black box. I saw "video_rec" in VSH documentation but I wasn't sure that your implementation was an exploit of that. That's probably why I couldn't understand your code. :smile: 
So yeah I guess the only solution would be to recode a brand new plugin using another recording method. I would like to do it myself but it would probably need awesome skills! 

Thanks for explaining how the video recording was working, I was really curious about that.

EDIT: Maybe this can be a start: https://github.com/dsokoloski/open-rp ?
