### ISSUE TITLE
Loading games from HDD using webman mod 

### ISSUE THREAD

**Issue by Thibobo** [aldostools/webMAN-MOD#132]
loading games from hdd with webman mod version 1.47.08 while cfw syscalls are disabled is not working. It has always worked but by updating to rebug 4.82.1 DEX i wanted to use 1.47.08 but it seems not to be working unafortunately.

**Comment by aldostools** [comment]
Since build 1.45.10, by default, all the CFW syscalls (including Cobra's syscall 8) are disabled when the combo R2+TRIANGLE is used. This was changed to provide higher protection to the user when PSN/SEN is accessed.

To allow mounting games with the CFW syscalls disabled, go to /setup.ps3, change the option PS3MAPI to ENABLE, save and restart the system.

The option is next to the combo "DEL CFW SYSCALLS" in  the section "XMB/In-Game PAD SHORTCUTS".

**Comment by Thibobo** [comment]
so there is no way to load games with webman with all syscalls disabled from boot? Can this "loading or cobra feature" be whitelisted in some sort of way just like whitelisting homebrews with the cfg file?

**Comment by aldostools** [comment]
If *ALL* CFW syscalls are disabled, then there is no way to load games with syscalls disabled, because they are loaded using Cobra syscall 8 and that is one of the CFW syscalls disabled. Once it is disabled, there is no way to re-enable the syscalls unless you restart the system.

With the option "PS3MAPI" enabled, *ALL* CFW syscalls are disabled, except syscall 8 that is *partially disabled*. As the syscall 8 is partially disabled, webMAN MOD can re-enable all the syscalls again.

The is no whitelist for syscalls. You can use the tag "[online]" in the file name of the ISO or folder to auto-disable syscalls (all or partially-all).

**Comment by Thibobo** [comment]
and can "PS3MAPI" be enabled on boot to disable cfw syscalls and partially disable the cobra syscall 8? So games can still be loaded with webman? If not is it something you'd look for in future updates?

**Comment by aldostools** [comment]
The option "PS3MAPI" enabled works for any method used to disable the syscalls through webMAN MOD: 
- using the option "Disable CFW syscalls and delete history files at system startup"
- through the combo R2+TRIANGLE 
- using web commands.

**Comment by Thibobo** [comment]
so there won't come a option to disable cfw syscalls and partially disable syscall 8 on boot? So this way we don't need to press any key combinations or web commands, this way people can not by accident forget to do it.

**Comment by aldostools** [comment]
If "Disable CFW syscalls and delete history files at system startup" and  "PS3MAPI" is enabled, it should do what you want.

Anyway PSNpatch is a specialized plugin for that purpose and it integrates well with webMAN MOD. 
Just use it.

**Comment by Thibobo** [comment]
Like this? https://imgur.com/ZEBZMiD

Where can i find the psnpatch plugin? i remember the pkg but never heard of the plugin.

**Comment by aldostools** [comment]
Yes like that.

You can find PSNpatch here:
http://store.brewology.com/ahomebrew.php?brewid=244

**Comment by Thibobo** [comment]
thanks alot for the help, works like you told! very much appreciated! thanks!

I will look into PSNpatch plugin. thank you

**Comment by Thibobo** [comment]
When i launch a ps3 game i get a vsh message saying "offline", what does this mean? (Maybe how can i disable this?) thnx!

**Comment by aldostools** [comment]
Please check your settings in /setup.ps3

There is an option to force play offline. Maybe you enabled it.

Or restore the default settings deleting the config file, then configure webMAN again:
/delete.ps3?wmconfig

**Comment by preacherhack** [comment]
Can i re-enable my syscalls after disabling it

**Comment by aldostools** [comment]
Yes, if the Cobra/HEN payload allows it. Otherwise you have to reboot to get them enabled again.

In Evilnat you have the option Network > Custom Firmware Tools > Cobra > Create Syscalls

I'm not sure if PS3HEN has implemented this feature yet.
