### ISSUE TITLE
webMAN Fails to Load on Boot

### ISSUE THREAD

**Issue by sgern** [aldostools/webMAN-MOD#137]
PS3 Model: CECH-2001A
CFW: Rebug 4.82.2 REX
webMAN-MOD Version: 1.47.08
HDD: 1.5TB HDD, Reduced to 1TB via MHDD
Other Plugins: CCAPI v2.80rev3, PSNPatch

When I start up my PS3, sometimes instead of quickly going to the user selection screen and notifying me of which plugins have loaded (webMAN, PSNPatch, CCAPI), it lags for a few seconds before going to user selection, and does not say that webMAN loaded. The webMAN folder doesn't work when this happens.

**Comment by aldostools** [comment]
Please try without CCAPI and if the issue still persists, try loading webMAN MOD alone.

Also verify in /setup.ps3 that the startup notification is _not disabled_ and that content scan on startup is preferably _disabled_.

Also confirm that the path of **webftp_server.sprx** is listed in _/dev_hdd0/boot_plugins.txt_
(Unlike previous versions of Rebug that loaded webMAN directly from dev_flash, Rebug 4.82 requires webftp_server.sprx installed on HDD and listed in boot_plugins.txt)

**Comment by sgern** [comment]
I performed the steps you listed. I'll tell you if it still doesn't work.

EDIT: Totally forgot about this. It works just fine now.

**Comment by Missingmew** [comment]
Sorry for hijacking this issue, but im experiencing the same problem.
When starting the system, the "webman loaded" message doesnt appear (sometimes with the couple seconds lag, sometimes with no delay) before telling me which game is mounted (I have automounting for the last game enabled). Launching the game after that will result in a blackscreen softlock. webman settings are unavailable (website cannot be found).
Only fix is to restart and have a bit of luck.
I tried disabling searching for new content on startup but this hasnt helped.

System Info:
CECH-2004
Rebug 4.82.2 REX
webman 1.47.08
480G Sandisk SSD
No other Plugins

Additional notes:
I experienced the same issues before on a CECH-2504 system with the same configuration aside from that.
Also, this issue started appearing after updating from rebug 4.81, the issue wasnt present there (even with content search on startup enabled).

EDIT:
Turns out i _did_ have a plugin enabled which seems to have clashed with webman.
For those who run rebug like me, try disabling the XMB debug options from rebug toolbox (only when you disable it you get a note that its a plugin, hence i didnt know that it was one). All startups so far worked fine, ill edit again if things go bad again.
