### ISSUE TITLE
Last game is always auto loaded (even if disabled)

### ISSUE THREAD

**Issue by 444nonymous** [aldostools/webMAN-MOD#15]
https://github.com/aldostools/webMAN-MOD/blob/bf0afa2312a6216221dd38c022073a85b06ed9a2/updater/pkgfiles/USRDIR/webftp_server_lite.sprx

After testing the new release to fix the FTP problem I have noticed a new problem: "load last played game on startup" is always working even if not selected.

I deleted all cache and config files, and the problem persists. I'm using webman lite and latest Rebug.

**Comment by aldostools** [comment]
Thank you for your feedback. I really appreciate your help reporting bugs, specially due the several scenarios that I have to test.

Indeed this bug was quite old... I just fixed it in the commit 0da652f. You can download the updated binaries from:
https://github.com/aldostools/webMAN-MOD/releases/1.43.35

**Comment by 444nonymous** [comment]
This one is fixed
