### ISSUE TITLE
wrong free disk space info

### ISSUE THREAD

**Issue by houcembc** [aldostools/webMAN-MOD#158]
webMAN 1.47.09 MOD in web interface Files tab, free disk space info is showing unit MB instead of GB

![image](https://user-images.githubusercontent.com/8948107/47615890-cc84ef80-dab5-11e8-843b-255227407553.png)

![image](https://user-images.githubusercontent.com/8948107/47615893-df97bf80-dab5-11e8-8253-fdcde992ada7.png)

**Comment by catara** [comment]
why is "wrong"?

**Comment by aldostools** [comment]
The difference is due I used 2 different functions to report the free space.

The free space reported in the root screen is the value returned by the **syscall 840** (SC_FS_DISK_FREE).

The free space reported at the bottom of the file manager is the value returned by the function _cellFsGetFreeSize_ used in the function **get_free_space()** found in file.h

The syscall 840 was used instead of _cellFsGetFreeSize_ because it also returns the device size, required to calculate the %.

The function get_free_space was created long time ago and it used the function _cellFsGetFreeSize_ because the device size was not needed for that function.

The following update to the function in file.h has not been tested (I can't test it ATM), but I guess it would fix the "issue":
```C+
static u64 get_free_space(const char *dev_name)
{
#ifdef USE_NTFS
	if(is_ntfs_path(dev_name))
	{
		struct statvfs vbuf;
		char tmp[STD_PATH_LEN];
		strcpy(tmp, dev_name); tmp[10] = ':', tmp[12] = 0;
		ps3ntfs_statvfs(tmp + 5, &vbuf);
		return ((u64)vbuf.f_bfree * (u64)vbuf.f_bsize);
	}
#endif
	u64 freeSize = 0, devSize = 0;

    #define SC_FS_DISK_FREE		840
	{system_call_3(SC_FS_DISK_FREE, (u64)(u32)(dev_name), (u64)(u32)&devSize, (u64)(u32)&freeSize);}
	return freeSize;
/*
	u32 blockSize;
	u64 freeSize;

	if(cellFsGetFreeSize(dev_name, &blockSize, &freeSize)  == CELL_FS_SUCCEEDED) return (freeSize * blockSize);
	return 0;
*/
}
```
