### ISSUE TITLE
How to Mount Games with deactivated syscall

### ISSUE THREAD

**Issue by ChrOn0os** [aldostools/webMAN-MOD#160]
Hello i've upgraded my cfw (4.81 Rebug CEX to 4.82 Rebug CEX)

And, when I was in 4.81, I was using Deank's webman, and I could launch games with syscalls disabled, how to do the same with WebmanMOD?

Thanks !

**Comment by aldostools** [comment]
By default webMAN MOD does not allow to mount games with CFW syscalls disabled, because syscall 8 (used by Cobra to mount games) is also disabled.

There is an option in /setup.p3 that allows to keep syscall 8 semi-enabled when the CFW syscalls are disabled. Look for the option **PS3MAPI** under _**XMB/In-Game PAD SHORTCUTS**_. It is important to remark that enabling that option the CFW becomes more detectable when you access PSN, which could result in an account or system ban or both.

**Comment by ChrOn0os** [comment]
Perfect, thanks !
