### ISSUE TITLE
Feature Request: Add option/toggle to automatically use ps1_netemu as default

### ISSUE THREAD

**Issue by emkultra64** [aldostools/webMAN-MOD#165]
For most games, `ps1_netemu.self` offers a better (or at least more accurate) experience than `ps1_emu.self`, especially for 2D games with lots of horizontal scrolling. There are, however, a few edge cases where `ps1_emu` might be preferable because of differing compatibility or performance for some games.

While it is possible to just swap the file names to ensure that all PS1 ISOs and discs load with `ps1_netemu` by default, this creates a conflict with downloaded PS1 Classics that use netemu, as they'll end up using `ps1_emu` instead. Copying `ps1_netemu` and renaming it to `ps1_emu` without removing the original netemu is the most non-intrusive solution, but this defeats the override of holding R2 to change emus and makes the original `ps1_emu` inaccessible for those edge cases.

Therefore, having a toggle in webMAN Setup to choose a default PS1 emulator loaded upon mounting an ISO would offer a much simpler solution from the user side of things.

**Comment by aldostools** [comment]
Yes, some games work better with ps1_netemu... That's why we have the check box for "**ps1_netemu**" next to the option PLAYSTATION® under the section "Scan for content" of /setup.ps3

https://github.com/aldostools/webMAN-MOD/blob/master/include/setup.h#L550
https://github.com/aldostools/webMAN-MOD/blob/master/include/psxemu.h#L20
https://github.com/aldostools/webMAN-MOD/blob/master/include/_mount.h#L1402

**Comment by emkultra64** [comment]
Thanks! I didn't know this feature existed. I'm going to try that option out tonight and see if I can do something to make sure this is documented in more places, because the netemu/emu swapping is extremely useful and not especially well-reported in the community even though it's so helpful.
