### ISSUE TITLE
How to compile ps3netsrv for openwrt brcm?

### ISSUE THREAD

**Issue by kartale** [aldostools/webMAN-MOD#168]
I have a problem with compiling package for openwrt. using raspbery_P sources. getting error 
`20141001/bin/../lib/gcc/mips-linux-uclibc/4.6.4/../../../../mips-linux-uclibc/bin/ld: main.o: Relocations in generic ELF (EM: 3)
main.o: could not read symbols: File in wrong format`
anybody can say, ho to fix it?

**Comment by ghost** [comment]
Isn't that Broadcom a MIPS processor (usually BCM4705)? While rPi is ARM.

**Comment by kartale** [comment]
Hi. yep, that's right - bcm4708_MIPS. so what sources should i use? can u provide link?

**Comment by ghost** [comment]
To be honest, i don't know. I just noticed that ARCH don't match. Wait until aldo or someone else will answer, or maybe try precompiled mips binaries:

https://github.com/aldostools/webMAN-MOD/tree/master/_Projects_/ps3netsrv/bins/old/Linkstations%20(arms_mips_ppc)

https://github.com/aldostools/webMAN-MOD/tree/master/_Projects_/ps3netsrv/bins/old/mips32

**Comment by kartale** [comment]
precompiled bin *mipsel not work at all. *mipseb - looks like starting, but there is no stdout andps3 not see device. so i think i need to compile for my device (bcm4707). what source should i use for compile ps3netsrv_mipseb for my platform? 

  openwrt 14.07 (3.10.49 core), BCM4707
configured openwrt toolchain, but can't compile ps3netsrv

**Comment by VRtinker** [comment]
> precompiled bin *mipsel not work at all. *mipseb - looks like starting, but there is no stdout andps3 not see device. so i think i need to compile for my device (bcm4707). what source should i use for compile ps3netsrv_mipseb for my platform?
> 
>   openwrt 14.07 (3.10.49 core), BCM4707
> configured openwrt toolchain, but can't compile ps3netsrv

Hey, I'm not sure if this will help you, but a few months back I compiled builds for ARMv7 and Linux 64bit of ps3netsrv, and actually also made a [pull request](https://github.com/aldostools/webMAN-MOD/pull/153) for them to be integrated in this repository (which hasn't been considered, so far). At any rate, I compiled the ARMv7 build directly from the router, making only a single adjustment in the make file of the source (I used the actual ps3netsrv source, so no raspberry pi or what have you variant). I explained this a bit more in [my fork](https://github.com/VRtinker/webMAN-MOD/tree/master/_Projects_/ps3netsrv/bins/OpenWRT), but essentially that's the only modification to the source that you need.

Try using the official source code (erasing the Makefile.linux file) while using my modified Makefile (perhaps you could modify my Makefile "OUTPUT" parameter to "ps3netsrv_mips" instead of the current "ps3netsrv_arm"). I actually don't see why it shouldn't work.

Good luck!

**Comment by bfoot** [comment]
Hi.
I have Asus RT-N66U with Tomato firmware.
I install ps3netsrv from entware.
But when I "update XML" from webMAN, ps3netsrv on router error (double // in path)

INFO:  [18:31:44.723] Waiting for client...
INFO:  [18:31:47.762] Connection from 192.168.1.45
DEBUG: [18:31:47.764] [725173488] openDirectory
DEBUG: [18:31:47.765] [725173488] openDirectory done
DEBUG: [18:31:47.766] [725173488] openDirectory
ERROR:  [18:31:47.833] Failed to open directory: /opt/share/ps3netsrv//GAMES [auto]
DEBUG: [18:31:47.833] [725173488] openDirectory done
DEBUG: [18:31:47.834] [725173488] openDirectory
ERROR:  [18:31:47.869] Failed to open directory: /opt/share/ps3netsrv//GAMEZ
DEBUG: [18:31:47.869] [725173488] openDirectory done

**Comment by Joonie86** [comment]
Please try this one

https://github.com/zefie/openwrt-zefie

We are closing this issue since this is not supported by us.
