### ISSUE TITLE
VSH doesn't workin

### ISSUE THREAD

**Issue by DistractedYOBA** [aldostools/webMAN-MOD#180]
With new release VSH stops workin. Says Russian language doesn't supported. If i'm switching to english nothing happens.

**Comment by aldostools** [comment]
Please try this:
1- Change the system language to English.
2- Go to /setup.ps3 and check that the shortcuts for VSH Menu is enabled.
3- Return to XMB and press SELECT for about 5 seconds

**Comment by DistractedYOBA** [comment]
It works, but if I'm switching back to russian error occurs again.

**Comment by aldostools** [comment]
It is not an error, VSH menu is disabled intentionally if Russian language is selected.

VSH menu freeze the system if Russian language is selected.
The reason is currently unknown... I suspect it is caused by the bliting of Cyrillic font set. 
The problem does not occurs with other languages (including the ones using Unicode characters like Korean or Japanese).

The feature is disabled to prevent instability of the system until the bug is resolved.
