### ISSUE TITLE
FTP server is broken

### ISSUE THREAD

**Issue by 444nonymous** [aldostools/webMAN-MOD#20]
After "Fixed broken support for FlashFXP" -> https://github.com/aldostools/webMAN-MOD/commit/f2395afa766f9e13c18774cb27b5bb2a18b481f5

I can access the FTP server but it's completely empty, it does not list any file or folder.

**Comment by aldostools** [comment]
Thank you for the bug report. 
Please include details about the FTP client and the settings used to connect. Also try using active connection instead of pasive connection.

I have tested the webMAN's FTP server with the following clients: Filezilla, FlashFXP, Windows FTP (command line & Windows Explorer) and the web browsers: Chrome, Mozilla, Edge, MSIE. All show the directory listing using the stock settings.

**Comment by 444nonymous** [comment]
Firefox and some others work.

But there is something wrong because It does not with other clients like -> http://www.leapware.com/download.html

**Comment by aldostools** [comment]
Thank you for the link. I have installed leapFTP 3.1.0 and it is listing the files properly using the stock settings. The file transfer seems to be working fine too.
http://aldostools.org/temp/test/leapFTP.jpg

Please check the settings that you're using or try to use a different client.

I tested with these binaries:
https://github.com/aldostools/webMAN-MOD/releases/1.43.36

**Comment by 444nonymous** [comment]
I'm trying again and I can't see any problem with my firewall or configuration. Nothing blocked, but I can't see anything listed, empty. Even the FTP log looks fine. It works fine in Firefox.

[16:25:30] LIST -la
[16:25:30] 150 OK

**Comment by aldostools** [comment]
LIST -la was not supported. Only LIST -l and LIST -al. Please try with this binary:
http://aldostools.org/temp/webftp_server.sprx

For some reason, leapFTP worked fine for me with the stock settings.

**Comment by 444nonymous** [comment]
Now it's working. "-la" is used in some FTP servers when "show hidden files" is selected. Total commander uses -la too.

I'm pretty sure I've always been using -la with webman. So you changed something, because -la worked fine before.

**Comment by aldostools** [comment]
Yes, the reason why it stopped working is that in earlier versions of webMAN MOD, any parameter used in LIST, NLST, MLST, MLSD was ignored.

Since 1.43.36, webMAN supports LIST parameters to filter the directory listing (as it should be). However, the special commands like -l, -la or -al should be ignored; or webMAN would think that you're trying to list files named like "_-la_".
