### ISSUE TITLE
Games or webMAN Setup only shows when Grouping is disabled.

### ISSUE THREAD

**Issue by Joonie86** [aldostools/webMAN-MOD#200]
I think the recent changes on games_xml.h causes this bug. Strangely enough, this currently happens on my CEX unit only (HEN), but fine on DEX (HEN).

Maybe something to do with "webman_config->nogrp" ?

![image](https://user-images.githubusercontent.com/8692743/58702367-741f1480-835a-11e9-8c5b-73bff4aa4ec8.png)

![image](https://user-images.githubusercontent.com/8692743/58702415-9f096880-835a-11e9-9c16-3d3af2e29185.png)

**Comment by aldostools** [comment]
ATM I'm at work... you can compile webman with this games_xml.h (remove .txt extension) or wait until I get home. I think the issue was caused by the concatenated string constant "&lt;/table>" in line 1048. I reverted that code as it was before. 

[games_xml.h.txt](https://github.com/aldostools/webMAN-MOD/files/3241257/games_xml.h.txt)

**Comment by Joonie86** [comment]
> ATM I'm at work... you can compile webman with this games_xml.h (remove .txt extension) or wait until I get home. I think the issue was caused by the concatenated string constant "</table>" in line 1048. I reverted that code as it was before.
> 
> [games_xml.h.txt](https://github.com/aldostools/webMAN-MOD/files/3241257/games_xml.h.txt)

I just tried the code above, but unfortunately the issue remains. I'll have to wait for you.

**Comment by aldostools** [comment]
You can try compiling with games_xml.h from 1.47.20 to check if it works... 
I the other changes don't seem to be related to your issue. Maybe the webMAN_**.xml for your selected language is corrupted /dev_hdd0/game/XMBMANPLS/USRDIR/FEATURES

[games_xml.h.txt from 1.47.20](https://github.com/aldostools/webMAN-MOD/files/3241379/games_xml.h.txt)

**Comment by aldostools** [comment]
It would be helpful if you could post or send me your corrupted mygames.xml

**Comment by Joonie86** [comment]
> It would be helpful if you could post or send me your corrupted mygames.xml


[mygames (2).xml.txt](https://github.com/aldostools/webMAN-MOD/files/3241625/mygames.2.xml.txt)

as shown in the pictures, I'm using English.

**Comment by aldostools** [comment]
I did a quick check of your mygames.xml and it looks good, which means that the code in games_xml.h is ok.

Please check if this file exists or if it is corrupted:
/dev_hdd0/game/XMBMANPLS/USRDIR/FEATURES/webMAN_EN.xml

Also check that it has a segment named "seg_webman_links_items"

**Comment by Joonie86** [comment]
> I did a quick check of your mygames.xml and it looks good, which means that the code in games_xml.h is ok.
> 
> Please check if this file exists or if it is corrupted:
> /dev_hdd0/game/XMBMANPLS/USRDIR/FEATURES/webMAN_EN.xml
> 
> Also check that it has a segment named "seg_webman_links_items"

It's identical to what you have in your repo.

**Comment by aldostools** [comment]
Ok, I will check the xml when I get home. Maybe it's a missing character or a conflicting key name in the xml.

To to be sure, check if you are using or NOT the noncobra edition. It creates a fb.xml linked to jbgames.xml instead of mygames.xml to prevent freeze caused by wm_proxy not being remapped.

**Comment by Joonie86** [comment]
> Ok, I will check the xml when I get home. Maybe it's a missing character or a conflicting key name in the xml.
> 
> To to be sure, check if you are using or NOT the noncobra edition. It creates a fb.xml linked to jbgames.xml instead of mygames.xml to prevent freeze caused by wm_proxy not being remapped.

I always use full edition and I can easily fix this by reverting back to 1.47.20

**Comment by aldostools** [comment]
The issue was caused by a typo in this line (where it says PS2 should say PS1):
https://github.com/aldostools/webMAN-MOD/blob/2aad059563cc426d8bbfbb61b79663b782c85760/include/games_xml.h#L795

Anyway the latest commit fixes the bug through the implementation of a new typedef optimized for string concatenations.
