### ISSUE TITLE
Encoding issue with unicode listing /net games on gamelist (XML/HTML) and file manager

### ISSUE THREAD

**Issue by Joonie86** [aldostools/webMAN-MOD#206]
![image](https://user-images.githubusercontent.com/8692743/59125950-a4e1e980-8918-11e9-8339-eb6c67d0d203.png)

![image](https://user-images.githubusercontent.com/8692743/59125959-ac08f780-8918-11e9-98f4-783f002ed675.png)

[mygames.xml.txt](https://github.com/aldostools/webMAN-MOD/files/3267194/mygames.xml.txt)

I attached pictures and my xml renamed to TXT, mind taking a look?

*EDIT
Looks like this also happens on both 1.47.22 and 1.47.21. I'll also check to see if my locale setting on Windows affect this.

**Comment by aldostools** [comment]
What is the exact name of the file in the file system? 
Does it include special characters like ™, ® or © or unicode characters?
Does it happen only with /net files or also with local files (hdd0, ntfs or usb)?
Does the file name show fine if you browse to that folder in web file manager?

I see only these entries show special characters:
Alice+Madness+Returns-BLUS30607(UI%B8%B8+%C7%D1%B1%DB).iso
Ninja%2BGaiden%2BSigma%2B2%2BKorean_For_Cobra.iso

BTW Alice is the entry 0034 (first after sort) ;)

EDIT:
IIRC there is an unresolved bug showing files with unicode characters on /net
Maybe due double encoding or decoding to UTF8... Not recall if it's caused by ps3netsrv.exe or Windows.

**Comment by Joonie86** [comment]
> What is the exact name of the file in the file system?
Alice Madness Returns-BLUS30607(UI만 한글).iso
> Does it include special characters like ™, ® or © or unicode characters?
Nope
> Does it happen only with /net files or also with local files (hdd0, ntfs or usb)?
Currently only via nethost, I'm transferring this to HDD0 atm
> Does the file name show fine if you browse to that folder in web file manager?
Nope

I remember seeing this displayed correctly while back using CFW. I can't remember when this started. I'll report you back later with further testing. So far, 1.47.20~1.47.22 all do this with "ps3netsrv build 20170310 (mod by aldostools)"

**Comment by gfhhhg** [comment]
Can you display the game disc icon after the game is fully loaded, so it won't crash when you click too fast

**Comment by aldostools** [comment]
> Can you display the game disc icon after the game is fully loaded, so it won't crash when you click too fast

The disc icon is shown automatically by VSH when it completes the load process.

I can force a fake_insert_event after mount the game but it is not recommended since VSH will show the disc icon when it completes the load of the game. The fake_insert_event only would result in showing two disc icons.

**Comment by Joonie86** [comment]
@aldostools 

![image](https://user-images.githubusercontent.com/8692743/59141219-b994a080-895d-11e9-9012-5c1500b78081.png)

Apparently the issue only occurs when the game list was generated from net0. It reads fine from dev_ntfs

**Comment by gfhhhg** [comment]
Thank you for your answer. I mean, can I hide the disc icon before the game is fully loaded so that it won't crash too fast

**Comment by aldostools** [comment]
> Thank you for your answer. I mean, can I hide the disc icon before the game is fully loaded so that it won't crash too fast

The disc icon is shown automatically when VSH has finished loading the game.

If you're using PS3HEN, it could be an issue with the payload. Not a webMAN issue.

**Comment by gfhhhg** [comment]
Thank you for your answer, it is indeed the use of hen

**Comment by aldostools** [comment]
> I remember seeing this displayed correctly while back using CFW. I can't remember when this started. I'll report you back later with further testing. So far, 1.47.20~1.47.22 all do this with "ps3netsrv build 20170310 (mod by aldostools)"

If the game was in JB folder format it probably showed the localized name from PARAM.SFO

In the beta **1.47.22.2** I added support to show the game title from the remote &lt;iso-file-name>.SFO (cached to /hdd0/tmp/wmtmp)

Yesterday I expended several hours trying to resolve the display of the unicode characters. I managed to display certain unicode characters (not korean), but it caused other issues accessing the path. I think the issue is related to the encoding functions (utf8enc, htmlenc, htmldec in html.h  and add_net_game in games_html.h) and ps3netsrv function process_read_dir_cmd sending the file names without encoding the characters to UTF-8.

To support unicode characters it may require to update the dir listing protocol between wMM and ps3netsrv. I think it would require a new function process_read_dir_utf8 and the encoding/decoding functions in wMM may need to be updated too.

**Comment by WishTomorrow** [comment]
i got same encoding issue in my PS4 with chinese folder name. it was working fine in the very old version 1.45 before, but after i upgraded it to 1.47.27, it cannot show the chinese game name anymore. eventhough i downgraded to the old version before. it still cannot show the chinese name anymore. any solution for this issue, is it posibile to change the encoding for chinese langueag only? e.g. BIG5 or GB2312? thank you so much.

**Comment by aldostools** [comment]
Please, check if this build of ps3netsrv works:
[ps3netsrv.zip](https://github.com/aldostools/webMAN-MOD/files/4765951/ps3netsrv.zip)
[webftp_server.zip](https://github.com/aldostools/webMAN-MOD/files/4766885/webftp_server.zip)

ps3netsrv implements on Win32 the utf8_to_ucs2 from the linux version

 Also try with the webftp_server.sprx in the zip above.

**Comment by WishTomorrow** [comment]
i just tested your new complied file, the issue seems still not fix, but i found there are two games with chinese folder names were loaded in my game list, the others games still fail to load it except i change the folder name to english only.
i am using the REBUG 4.86.1 LITE and weman mod 1.47.28 now.
thank you so much for prompt response.
[games.zip](https://github.com/aldostools/webMAN-MOD/files/4770279/games.zip)
