### ISSUE TITLE
Settings Not Applying

### ISSUE THREAD

**Issue by AbeNormal** [aldostools/webMAN-MOD#210]
PS3Hen 2.2.2 w/ MOD 1.47.22

Checked Disable Grouping of Content and Disable webMEN Setup enty - saved and rebooted

Aren't performing the function as groups are still showing and setup entry is still showing.  Opened settings again to confirm checks and they are still marked.

**Comment by aldostools** [comment]
It is not enough to  save the settings and reboot, if you have disabled the scan for content when the system starts (which is recommended to have it disabled)

After disable grouping of content, it is necessary to scan for content again using SELECT+L3 then refresh XMB (rebooting, running RELOADXMB or entering to an app and returning to XMB) to reflect the changes.

Did you try the latest beta or 1.47.22? If you haven't try the latest beta, please try it since it eventually will be promoted to .23

**Comment by AbeNormal** [comment]
I installed the beta and the problem was fixed! Thanks for such a quick response and for keeping this MOD developed for us!
