### ISSUE TITLE
Self-update Idea.

### ISSUE THREAD

**Issue by J0hnTR** [aldostools/webMAN-MOD#211]
Greetings!

As always, WebMAN-MOD is awesome!
Can I ask You to make it even more awesome by adding a feature of latest version downloading directly from its menu?

Thank you!

**Comment by aldostools** [comment]
Thank you J0hnTR for your suggestion. At the bottom of /setup.ps3 there is a link to the latest release page on github and another to the official forum on PSX-PLACE.

DeViL303 and other XMB modders provide links to download webMAN directly from XMB.

I have been avoiding to add an update link to webMAN.xml because it adds me extra work 😀

**Comment by J0hnTR** [comment]
Wow, answered so fast)

Yes, saw the link in a bottom line of Setup page, but unfortunately my PS3 shows me ssl-related errors when I either try to download WebMAN-MOD from github, or from PSX-PLACE..
But that's some very other story)

**Comment by J0hnTR** [comment]
Oops)

**Comment by aldostools** [comment]
Done
