### ISSUE TITLE
Gamelist not fully populating

### ISSUE THREAD

**Issue by pokeygithub** [aldostools/webMAN-MOD#213]
I have 428 iso games on ntfs drive, and 750 games in the GAMES folder on the network.  With version 1.47.09 I could see all of the games in version 1.47.23 I cannot.  I am downloading 1.47.23.2 now in hopes that this corrects the issue.

**Comment by aldostools** [comment]
Please update the **Plugin memory usage** found in the **"IDPS & MEM Setup"** section of /setup.ps3 

Builds previous to 1.47.23 had the [MC] option enabled by default, which allocates 3MB for scanning and sorting content. However, that option was disabled by default because it causes black screens on certain users.

You can simply go to /setup.ps3 mark [MC] and save the settings (no need to reboot). Re-scan again.

**Comment by pokeygithub** [comment]
That did it.  I also tried setting the memory to 1200 and that worked as well.  I did get a black screen but I think that is a bad iso in my collection.
