### ISSUE TITLE
Auto-select last game played & go back to the Games column 

### ISSUE THREAD

**Issue by 444nonymous** [aldostools/webMAN-MOD#22]
1. Since webman already remembers the last game played, why not auto-select it when browsing a list of games? If I open the PS3 folder, instead of selecting the first game in the list, point to the last played game. Select in this case means pointing the cursor over the game cover, not exec. Like it happens with irisman, it starts and selects the last game. You can also implement the feature to remember the last game played in every folder (PS3, PS2, PS1, PSP).
2. If autoplay is not enabled, when you select a game and press X, you get the info message of the game loading, but you are kept at the same game list and you have to manually go back to the root of  the Games column and select the game icon. It would be better if webman automatically went back (pointing to "webMAM Games") so the user could just go down and select the game icon when ready.

**Comment by aldostools** [comment]
1 Currently a list of the Last Played games can be listed clicking on the bottom of http://localhost/
The list is hidden by default to avoid cluttering.

On the XMB the things are a bit harder, due the VSH must be reloaded and the XML must be regenerated each time a game is mounted. I have been thinking about this idea, but I haven't found the time to implement it. One of the options that I have considered are using the VSH Menu to list the last games.

 2 I'll check what I can do...

**Comment by aldostools** [comment]
This test pkg include both features.
http://aldostools.org/temp/test/webMAN_MOD_1.45.01_Updater.pkg

**Comment by 444nonymous** [comment]
Webman is broken in the test build.

No FTP and "the page cannot be accessed" in the web browser when you try to do anything.

**Comment by 444nonymous** [comment]
Please read this comment, because the second feature is related to auto-play -> https://github.com/aldostools/webMAN-MOD/issues/17#issuecomment-254262467

**Comment by 444nonymous** [comment]
I've been able to test another buid, but it is very buggy, icons and "save / restart / etc" in webman options are missing.
1. First feature does not work. Listing starts at first game, no last game is remembered.
2. Second feature works very well, causing PS3 auto-play to work perfectly (with webman autoplay disabled). So it is a good finding that could help having 2 auto-play methods / options, PS3 and webman. Or maybe letting PS3 handle autoplay is the best option, it does not fail, and you can reduce some extra code / memory footprint needed to make webman's autoplay work fine.

**Comment by 444nonymous** [comment]
1 & 2 don't not work in the final build https://github.com/aldostools/webMAN-MOD/commit/435f0056fa143cfee1465a06226beabe294497ab It stays in the same place after the game is loaded (just like before this was changed).

**Comment by aldostools** [comment]
1. The Last Game list is implemented as menu in VSH Menu 1.12. Press SELECT, then L1 and select the game from the list.

Alternatively you can use the Last Game list found in "/" (root of web file manager).

A third method to select the Last Game is using SELECT+L1 or SELECT+R1.

Regarding the "buggy" release: If the /setup.ps3, /restart.ps3 or ftp server are not working is because you probably have enabled the ADMIN/USER MODE in /setup.ps3. That option is a security feature to allow remote access only when the user switches to ADMIN MODE using L2+R2+TRIANGLE. If the combo "ADMIN/USER MODE" is unchecked the plugin will boot in ADMIN MODE as before.

In my system if the auto-play is disabled, the folders on XMB are closed when a game is mounted, but
the "PLAY DISC" combo must be enabled. If "PLAY DISC" is unchecked, the XMB folders are not closed when a game is mounted. 

My suggestion: check "PLAY DISC" and "Auto-Play" options, and uncheck "ADMIN/USER MODE".

**Comment by 444nonymous** [comment]
OK, but it does not make sense to need a short cut activated like "PLAY DISC" to enable a different feature. It's impossible to tell that's the way it works. Sometimes pad short cuts are disabled.

If auto-play is disabled, then this new feature should be enabled. And that would be normal way of doing it automatically, like in the test builds that worked that way.

Thanks.

**Comment by 444nonymous** [comment]
Please consider always having features enabled by default even with all pad short cuts disabled.

If you use other plugins like artemis and disable pad short cuts to avoid any problem with webman, you still want webman to work the same and have the same features.

Thanks.

**Comment by Joonie86** [comment]
Closing old cases that have no further feedback. please use the latest version of wMM and report us
