### ISSUE TITLE
Fan policy to not set after disable CFW syscalls

### ISSUE THREAD

**Issue by CroissantFertile** [aldostools/webMAN-MOD#233]
New fan bug when u disable syscall after that u can't disable fan with L3 r2 triangle

**Comment by CroissantFertile** [comment]
Not in old versions

**Comment by aldostools** [comment]
Are you using any beta between 1.47.24.3 and latest 1.47.24.7? The issue was already reported here #227 and it was fixed in 1.47.24.3 beta.

Also the combo to enable/disable fancontrol is **L3+R2+START**, not the one that you said.

Indeed, there is not any function assigned to the combo L3+R2+TRIANGLE.
That combo could be detected as R2+TRIANGLE = disable cfw syscalls

**Comment by CroissantFertile** [comment]
Sry l3 r2 start

**Comment by CroissantFertile** [comment]
So? U closed this but the bug is still here

**Comment by CroissantFertile** [comment]
I am gonna tell u the bug another time because, after disabling syscall u can't disable the fan control with L3 r2 start

**Comment by aldostools** [comment]
It was fixed in build 1.47.24.3.

I will check the issue again when I get some free time.

**Comment by aldostools** [comment]
Closing issue. Fixed in build 1.47.24.8 beta.
