### ISSUE TITLE
Corrupted data in XMB with rebuild database

### ISSUE THREAD

**Issue by arcanacodec** [aldostools/webMAN-MOD#234]
I found a weird thing and I don't know if is really a bug but if you use HEN Hybrid Firmware Tools to remake the console database, once the console reboots a icon showing corrupted data of the size of 10 megabytes appears on XMB, if you delete it webMAN stops working.

**Comment by aldostools** [comment]
Thank you for your feedback. However, the bug report doesn't have enough information to produce a fix.

**Comment by arcanacodec** [comment]
Sorry for not being able to correctly explain the problem, I do not know much about how the console works but my blind opinion is that when the console redo the database it finds the webMAN directory and for some strange reason it defines it as corrupted data in the XMB games column. There will not be many people who will face this problem so you can close this if you want.

**Comment by aldostools** [comment]
Thank you for your feedback. If you manage to produce the bug consistently, please report back.

Closing for now.

**Comment by aldostools** [comment]
jolek @ PSX-PLACE provided more info about the subject in this link:
https://www.psx-place.com/threads/webman-mod-general-information-thread.9643/page-73#post-192626

I think one of the PARAM.SFO installed by webMAN is recognized as "corrupted" and result in "corrupted data" after rebuild the database.

I suspect it could be caused by this file /dev_hdd0/game/XMBMANPLS/PARAM.SFO

You can try replacing that PARAM.SFO with the one in the attachment, then rebuild to check if the corrupted data still happens.
[PARAM.SFO.zip](https://github.com/aldostools/webMAN-MOD/files/3373603/PARAM.SFO.zip)

**Comment by aldostools** [comment]
**jolek** @ PSX-PLACE reported that the issue was fixed installing the newest [PS2CONFIG.pkg](https://github.com/aldostools/webMAN-MOD/releases/download/1.47.25/PS2CONFIG.pkg)
https://www.psx-place.com/threads/webman-mod-general-information-thread.9643/page-74#post-192675

Closing the issue....  fixed in commit 2eb0bc6714c493e16289c16e69d39eaed12a0cbe
