### ISSUE TITLE
Webman Craches PS3

### ISSUE THREAD

**Issue by fantasmaxd** [aldostools/webMAN-MOD#238]
When I close the Multiman and go on Webman and start a game the PS3 freezes

**Comment by fantasmaxd** [comment]
Open the multiman, close the multiman, go to the webman and select a game.

The PS3 will freeze

If not freeze try again

**Comment by aldostools** [comment]
webMAN MOD uses wm_proxy.sprx to process the options selected on XMB.
To do it, it redirects the system plugin idle.sprx to wm_proxy.sprx

The problem is that multiMAN clears all cobra redirections, breaking webMAN MOD.
webMAN tries to restore the redirections when it detects that the user returned to XMB, but if you try to launch a game before this happen the system will freeze.

The problem indeed is multiMAN that breaks webMAN.

**Comment by fantasmaxd** [comment]
I tried a very old version and it did not freeze.
Version 1.**43**.25

**Comment by aldostools** [comment]
All versions prior to 1.46.00 use **webbrowser_plugin** as XMB proxy. That plugin is a system plugin and it not being redirected. So it's not affected by multiMAN. The problem with this plugin is that it's has a delay of various seconds loading/unloading.

To remove that delay, webMAN 1.46.00 and later builds use the plugin **wm_proxy** with ACT0 interface that receive the commands and pass them directly to webMAN. The XML cannot use wm_proxy directly because it's not whitelisted by XMB. To solve this, wm_proxy is spoofed as idle_plugin through a system map redirection.

multiMAN is removing that system redirection and breaking webMAN. Therefore the bug is in multiMAN, not in webMAN.

You can compile webMAN and use the old proxy (**webbrowser_plugin**) commenting the #define WM_PROXY in flags.h

**Comment by fantasmaxd** [comment]
ok, thank you
