### ISSUE TITLE
FTP timeouts after 20 seconds

### ISSUE THREAD

**Issue by 444nonymous** [aldostools/webMAN-MOD#239]
If set to 0 (before 0 = no timeout).

**Comment by aldostools** [comment]
It was changed to prevent the issue #209 transferring many small files.
Some connections were stuck forever because they didn't timeout.

If you need more time, you can set a timeout from 1 minute up to 255 minutes (4 hours 15 minutes).
The default timeout (0) now is 20 seconds, instead of no timeout (infinite).
