### ISSUE TITLE
PS3Netserv PSone Inconsistancy

### ISSUE THREAD

**Issue by Dracrius** [aldostools/webMAN-MOD#243]
Almost 9 times out of 10 when I try to refresh the game list Webman will lose and fail to see any psone games. When it does load them it fails to load any that use more then a single bin. Multiman will load and mount the same multi bin games like Spider-Man from Netserv without issue so it is possible to detect multi bin games without hand converting them all to single bin.

**Comment by aldostools** [comment]
webMAN MOD is not multiMAN...  Only single BIN/CUE are supported.

You need to convert the multi-bin to single BIN/CUE to use them in webMAN MOD.

The following text is a nice post by Coldheart2236 @ PSX-PLACE that explains how to do it.
https://www.psx-place.com/threads/multi-track-ps1-games.25263/page-2#post-194455

It would be easy enough to create your own cue sheet, from which you could 'mount' with DAEMON Tools Lite and then open with ImgBurn and then generate a single BIN and corresponding CUE file from which to use with backup managers. I use webMAN MOD myself, and I mount my ripped PS1 games in BIN/CUE format and have had no issues with this method so far. Here's a little tutorial for you. :)

In Windows, open Notepad and copy and paste the following:
Code:
FILE "Name of Track 1.bin" BINARY
  TRACK 01 MODE2/2352
  INDEX 01 00:00:00
Where "Name of Track 1.bin" is whichever the first and largest bin file is as this is the game data itself. For many games, that would be the end of the cue sheet since there is only one track (the bin image) and strictly speaking, you wouldn't really need one unless you were having problems with the game booting or functioning properly. A quick and easy fix if you did have any such issues. :)

But say you had a game with 20 tracks, your cue file would look like:
Code:
FILE "Name of Track 1.bin" BINARY
  TRACK 01 MODE2/2352
  INDEX 01 00:00:00
FILE "Name of Track 2.bin" BINARY
  TRACK 02 AUDIO
  INDEX 00 00:00:00
  INDEX 01 00:02:00
FILE "Name of Track 3.bin" BINARY
  TRACK 03 AUDIO
  INDEX 00 00:00:00
  INDEX 01 00:02:00
FILE "Name of Track 4.bin" BINARY
  TRACK 04 AUDIO
  INDEX 00 00:00:00
  INDEX 01 00:02:00
FILE "Name of Track 5.bin" BINARY
  TRACK 05 AUDIO
  INDEX 00 00:00:00
  INDEX 01 00:02:00
and so on.

With your complete cue sheet with all of the tracks accounted for in order, select 'Save As...' and with the drop-down menu 'Save as type:' From here, you can call it whatever you like, but make sure to add .cue at the end so it saves in the correct format and not as a text document. Save or afterwards place it in the same location as your different Track bin files.

From there, if you've got DAEMON Tools Lite (i.e. the free version) installed, the icon should be a lightning bolt and you can just double click on it. Alternatively right-click and select 'Open with' and open it that way. This will 'mount' the CUE file and then with ImgBurn (also free) you can create a single BIN and corresponding cue file of the individual tracks by clicking 'Create image file from disc' and then selecting the virtual drive that DAEMON Tools has assigned the cue file to. This should solve your problem. :)

**Comment by Dracrius** [comment]
This is  still not solved! the multi bin games was an extra comment especially after rechecking my library. Spider-Man for instance actually is a one bin game and it has yet to show up in my random lottery of psone games! At most I have had 17 of 27 now confirmed  single bin psone games show in webman. they will mount and play in for instance 'multiman' (is simply used as a control to  verify discs mount and play on ps3). And still the majority of the time it will load no psone games at all i must refresh the list multiple times and or reboot to  get lucky and have a varying amount of psone games list

**Comment by aldostools** [comment]
Try the build 1.47.25.3 it has a fix related to the parsing of the cue file.

Just need to re-download the latest build here or from brewology or update online.
