### ISSUE TITLE
Singstar load another title (error!)

### ISSUE THREAD

**Issue by Gauthier-L** [aldostools/webMAN-MOD#26]
Hi !

We have a problem with a Singstar games. If you use option "load another game" in Singstar, for loading an others songs we have an error : "Error!" , in webman.

When I select load another game, I umount the game and try to mount an other game.

Thanks so much !

**Comment by aldostools** [comment]
Singstar needs a physical PS2 disc to detect the swapped discs.

**Comment by Gauthier-L** [comment]
If I want use another Singstar PS3 ? I must use a PS2 disc ?

Actually :
- Insert blueray-disc game (GTA)
- In Webman I mount Singstar Ultimate Party
- I launch BD-disc Singstar Ultimate Party in XMB
- In Singstar Ultimate Party, I use "Load another disc"
- In webman I mount another Singstar for loading a new songs
- In webman habe "Error!", and if i click on "Error!", have a 400 Error from /dev_bdvd

Same Error if in first step I insert a PS2 Disc, etc.

Edit : If I run Multiman and in webman I launch a PS3Game have a "Error!"

**Comment by aldostools** [comment]
No. The PS2 disc is only needed to use the music from PS2 games in SingStar.

webMAN MOD throws an error if /mount.ps3 is used while a game is running. This warning error is intentional to prevent that the game quits accidentally while you're playing.

To bypass the error you must use **/mount_ps3**  (notice the underscore instead of a dot before "ps3").

In the page that shows the error there is a link that let you mount using /mount_ps3. Or first unmount the game, then mount the new game.

**Comment by Gauthier-L** [comment]
Oh Thanks ! It's run !
For next version, it's possible to add an option for mounting the singstar ps3 without the "Error!" ? It's just a request :P !

Thanks you so much !

EDIT : For PS2 Singstar, I must umount the PS3 game and mount PS2 ISO ? But no work (sorry) ! I've read on a forum : extract PS2 ISO to /mount_usb000/PS3ISO/SingStar-Pop/[PS2XXXXX] !

It's correct ? Thanks !

**Comment by aldostools** [comment]
Thank you for your feedback. The Error! is a warning message that I don't plan to remove.
It can be bypassed easily clicking one of the links on the screen or mounting with /mount_ps3

To use the PS2 SingStar games on PS3 SingStar, the PS2 ISO must be extracted as folder in /dev_hdd0/PS2DISC for ISOs stored on ntfs or hdd0; /dev_usbxxx/PS2DISC for ISOs stored on USBxxx.

For JB games (PS3 games in /GAMES folder) extract the PS2ISO in the root of the game folder (where PS3_DISC.SFB is found) and name the folder so it contains the string "[PS2". e.g. "[PS2 Disc] SingStar 1"

Using the full edition, the PS2 games will be listed on the mount screen of the web.

You can manually mount the PS2 game using /mount.ps2. The game will be mounted in /dev_ps2disc instead of /dev_bdvd

For additional support, please ask in PSX-Place forum.
