### ISSUE TITLE
webMAN MOD 1.45.00

### ISSUE THREAD

**Issue by RandQalan** [aldostools/webMAN-MOD#27]
Has a problem with pkg install it disables fan control and causes over heating for big pkg

**Comment by aldostools** [comment]
Please provide more information to help me reproduce this issue, to be able to debug it.

**Comment by RandQalan** [comment]
It happened when I was doing a muti install of pkg 
it happened when it was over a 2G size pkg
it shut down with red blinking led 
AFAIK it was either corrupt install or heat shutdown not sure

**Comment by aldostools** [comment]
Thank you for your feedback. 

Apparently the overheat was caused because the pkg install combo is running in the same thread of the fan controller. In consequence, the function that waits for the pkg installation was also pausing the fan controller until the pkg finished the installation.

To fix this issue now the plugin is creating a new thread for the pkg installation.

Please try with the binaries in the version 1.45.01
https://github.com/aldostools/webMAN-MOD/releases/tag/1.45.01

**Comment by RandQalan** [comment]
Thank you :)

What is the mute combo ?

**Comment by aldostools** [comment]
The mute is not a combo. It is the option "No SND0.AT3" in /setup.ps3 settings.

It basically redirects the /dev_bdvd/PS3_GAME/SND0.AT3 to an empty entry.

It is intended to avoid noise when a game is auto mounted at startup.
