### ISSUE TITLE
PS3MAPI not connecting because of Remove Syscalls combo disabled by default in settings

### ISSUE THREAD

**Issue by LezZoOo** [aldostools/webMAN-MOD#273]
PS3MAPI can't connect by default. To solve the issue i had to enable the Remove Syscall XMB/In-Game combo. If you make this combo enabled by default will solve the problem.
PS3MAPI is used more than before now because CCAPI does not work on PS3HEN, but PS3MAPI works.

**Comment by aldostools** [comment]
The following image is a screenshot of the default settings:
![image](https://user-images.githubusercontent.com/974897/66011274-758b5580-e490-11e9-9463-cc3cdccfb47f.png)

As you can see the combo for DEL CFW SYSCALLS is enabled by default.
However PS3MAPI is disabled by default because when it's enabled, the syscall 8 (used by Cobra API + PS3MAPI and PEEK LV1) is not fully removed. Instead it is fake disabled and it can be restored allowing to restore all CFW syscalls again.

As the syscall table is sent during PSN login, it is easy to detect the CFW syscall. For safety reasons, the PS3MAPI option is disabled by default.

Anyway it is suggested that the user configure the settings at least once, after wMM installation.
The PS3MAPI would be one of the options to change if needed.

**Comment by LezZoOo** [comment]
Yes sorry it is that option that cause my problem. Would be great if you could fix it, but if you can't i understand. Thanks for your work!
