### ISSUE TITLE
PS3HEN Block Servers does not work

### ISSUE THREAD

**Issue by ghost** [aldostools/webMAN-MOD#305]
Hey aldo

i think i found a bug

/browser.ps3$block_servers 

is not working on hen, it says blocking servers, but when i click to log in in the PSN it logs just fine

**Comment by aldostools** [comment]
That feature uses LV1 poke to patch the memory. HEN doesn't support LV1 poke.

It works fine on CFW

**Comment by marthoc** [comment]
Sorry to hijack issue - after using block PSN on CFW, how can I unblock?

**Comment by aldostools** [comment]
> Sorry to hijack issue - after using block PSN on CFW, how can I unblock?

The url of PSN servers are blocked in LV2 memory.

If you reboot they are restored, except if you have configured webMAN to block PSN on start up.

The web command **/browser.ps3$restore_servers**  restores url of PSN servers in LV2

The url of PSN servers are restored also when you block the CFW syscalls (R2+TRIANGLE), since the purpose of block them is to prevent to access PSN while CFW syscalls are enabled.
