### ISSUE TITLE
Question about PKG/ROM Launcher

### ISSUE THREAD

**Issue by floppyD** [aldostools/webMAN-MOD#358]
How exactly does PKG/ROM Launcher work? Does it point to the retroarch directory when launched? Or does it have its own folder?

**Comment by aldostools** [comment]
PKGLAUNCH_DIR "/PS3_GAME/USRDIR/cores" is redirected to RETROARCH_DIR "/USRDIR/cores". Then  
PKGLAUNCH_DIR is mounted as a game disc. When executed the EBOOT choose the emulator based on the folder of the ROM or on the file extension. If the extension is a video or audio file, Movian is executed with the mounted file as parameter.

https://github.com/aldostools/webMAN-MOD/blob/c07999af7b8917edc8c2f1af8f45818be9af5fbb/include/mount_misc.h#L84-L87

For ROMS stored on exFAT/NTFS or net, the process is similar but the ROMS/PKG Launcher is executed through the app_home/PS3_GAME icon, because the proxy plugins that emulate the SCSI response for exFAT/NTFS or net already use the /dev_bdvd path.

**Comment by floppyD** [comment]
Hi, thanks for the answer.

I'm asking this mainly because I'm trying to figure out why the RA launched by the PKG/ROM Launcher is missing stuff like my configs, assets and shaders, and why savestates seem to not work. I noticed that when first launched it creates a dummy "core" folder under PKGLAUNCH/PS3_GAME/USRDIR, with the same structure as RA's own core structure but completely empty. I thought it just needed to redirect that core folder to RA's own *core" under SSNE10000/USRDIR and grab the 2 cfgs, but that doesn't seem to happen since everything is still empty, even after mounting a disc (same with the folder under DEV_BDVD).

What's even weird to me is how it loads the core when I can't see anything under the launched RA's Load Core, I thought that maybe the redirecting thing is broken, but it's clearly not the case if a core is running.

**Comment by floppyD** [comment]
As an experiment I copied all the content under RA's USRDIR directory to PKGLAUNCH/USRDIR (but not EBOOT.BIN) and everything worked as I originally expected. 🤔
The only issue is that now I have 600MB of dupes.

**Comment by aldostools** [comment]
Thank you for your comment. I think I found something:
After mount the ROM I executed this command, and it seems the shaders show:
http://127.0.0.1/remap.ps3/dev_bdvd/PS3_GAME/USRDIR/cores&to=/dev_hdd0/game/SSNE10000/USRDIR/cores

I have to test adding that code in the plugin

**Comment by aldostools** [comment]
Try copying the webftp_server.sprx  in the zip to /dev_hdd0/plugins
[webftp_server.zip](https://github.com/aldostools/webMAN-MOD/files/4697610/webftp_server.zip)

This test build remaps the cores folder and subfolders to the copy in /dev_bdvd

**Comment by floppyD** [comment]
I didn't really notice any difference. Just to be sure, these directories should be populated, right?
![image](https://user-images.githubusercontent.com/29208110/83186380-d42dcf80-a102-11ea-8984-c477942c4cf3.png)

**Comment by aldostools** [comment]
You're right, there was a bug in the previous test. Here is a new build:
[webftp_server.zip](https://github.com/aldostools/webMAN-MOD/files/4697965/webftp_server.zip)

Here are the same paths using the new build (they show the same files in FTP too)
![image](https://user-images.githubusercontent.com/974897/83188114-32f04a80-a0fd-11ea-87cb-5520d87ffd02.png)

**Comment by floppyD** [comment]
Thanks a lot, it worked. What about other files under /SSNE10000/USRDIR/, can you symlink (that's what's happening there, right) them too?

**Comment by floppyD** [comment]
Whoops. Also a bit off-topic, is sMAN not compatible with ManaGunZ covers? They are all grey for me, despite showing up on XMB and coverflow.

**Comment by aldostools** [comment]
I remap (symlink) the folder /SSNE10000/USRDIR/cores to /dev_bdvd

I cannot remap the whole folder USRDIR because the EBOOT is different (it is resigned for retail).
The other files are config files that you can copy manually to /dev_hdd0/game/PKGLAUNCH/PS3_GAME/USRDIR

I want to keep the config files independent.

About sMAN and ManGunZ... Try asking in PSX-PLACE forum. I barely use these backup managers.

webMAN only uses a theme to make it look like sMAN's GUI

**Comment by floppyD** [comment]
It's fine, copying settings is not a big deal now that everything else works. Thanks again.

The sMAN I was talking about is actually "sLaunch GUI", didn't know there was another homebrew with that name. ManaGunZ is just what I use as the source for covers that show up on webMAN, I just thought maybe it was another issue, but anyway, I don't really use sLaunch either, I was just poking around.

**Comment by floppyD** [comment]
Oh never mind, "sMAN" and "sLaunch GUI" are the same plugin and it's developed by deank, not you, that's why you told me to ask on PSX-PLACE. I'm dumb, sorry.

**Comment by aldostools** [comment]
Yes webMAN + sMAN + sLaunch were made by the prodigious deank.

It's easy to get confused, because webMAN MOD uses a clone user interface that mimics sMAN and a modified version sLaunch. Indeed all my work is based on deank's projects. I only improved a few things to make it even better.
