### ISSUE TITLE
pkg installation broken

### ISSUE THREAD

**Issue by gosseux** [aldostools/webMAN-MOD#41]
I installed 1.45.08 full.  When trying to install pkg file from wMM ps3 web browser the ps3 display a message of the pkg installing then the ps3 freeze.

I reverted to 1.45.05 full and installation worked without issue.

All my pkg are stored like this:  usb/PKG/GAME NAME/GAME NAME.PKG
The .edat and/or .rap are in the same directory.  If you can create a link on file size to copy them to usb000/exdata it would be usefull.

edit: I try with 1.45.08 standard.  Same issue.

**Comment by aldostools** [comment]
Thank you for your feedback. After a long session of testing I found that the bug was caused by a buffer overflow (a small typo declaring the size of an array) in a completely unrelated module.

The issue should be fixed in the build 1.45.09. I'm sorry for the inconveniences that this bug has caused.

**Comment by gosseux** [comment]
Works properly now with build 1.45.09.

Thanks Aldo.
