### ISSUE TITLE
webMAN MOD 1.45.10 if disable CFW call on startup

### ISSUE THREAD

**Issue by RandQalan** [aldostools/webMAN-MOD#42]
Now if you have it set to disable CFW calls on start up can not mount any PS3 ISO

**Comment by Legended** [comment]
Cobra is still enabled with syscalls disabled so you should be able to switch games. I wouldn't recommend disabling syscalls at startup. If you use a homebrew app before signing it shows up in your history logs. Disabling syscalls right before signing in your history so that if you used a homebrew app before signing in it will clear the logs.

**Comment by RandQalan** [comment]
I have cobra enabled and it will not mount ISO 
But on .9 version it will so something is not working as intended

**Comment by RandQalan** [comment]
Close this issue did not notice the ability to PS3MAPI disable enable 
So not a bug just me not noticing the change

**Comment by jonaaa20** [comment]
Not a issue really, just enable PS3MAPI and you're done.

![screenshot_1](https://cloud.githubusercontent.com/assets/19306370/21965936/499866e2-db48-11e6-8edf-bc5dc212c57e.png)

**Comment by bdandy** [comment]
Confirm, Enabling PS3MAPI in settings works for me! Issue can be closed, not a bug
