### ISSUE TITLE
Hen bug 

### ISSUE THREAD

**Issue by james1233777** [aldostools/webMAN-MOD#449]
Fix webman on hen where webman mod disappears on the xmb when entering mmcm

**Comment by aldostools** [comment]
This is an issue in multiMAN / HEN, not in webMAN MOD.

AFAIK in HEN, the XMB entry of webMAN MOD is created by mapping the path of the XML in memory (sys_map_path)
multiMAN clears ALL mappings in memory when it starts.

Take in count that mmCM behaves like that since it was created. HEN didn't exist when that function was implemented.

**Comment by Masamune3210** [comment]
The same issue plays havoc with a lot of things and also causes webman to fail to mount games, causing a freeze instead. MM is old and has a lot of expectations that just arent the case anymore and it causes issues like this a lot

**Comment by james1233777** [comment]
Ah Allright thx
