### ISSUE TITLE
upload of files

### ISSUE THREAD

**Issue by DaviPx** [aldostools/webMAN-MOD#450]
I can see the files in my PS3 using the browser on my PC, and tested that I can download those files. It is possible to upload files using webman? 
I use FileZilla to do the FTP but it takes too long to show the folders.

**Comment by aldostools** [comment]
webMAN MOD uses only FTP protocol for upload/download files. HTTP is used only for download.

It is recommended to transfer files using 1gbit wired network instead of WiFi.

The fastest network setup is to connect the PC directly to PS3 without a router.
https://www.psx-place.com/threads/very-simple-way-to-direct-connect-ps3-to-pc.17052/

**Comment by DaviPx** [comment]
Thanks for the answer!
