### ISSUE TITLE
Idea: Add option to display game/disc version of a game in XMB in the same way tags/ID are displayed.

### ISSUE THREAD

**Issue by ghost** [aldostools/webMAN-MOD#538]
Adding this option would allow anyone wanting to have backups of different versions of a game show in a better manner through wMM. In addition, the game/disc version could be used to differentiate different ISOs and prevent them from being omitted through the new feature which does not display redundant games.

Another idea I have related to this would be to add an option to wMM to read a theoretical SUB_TITLE paramater in the param.sfo of a rip and display it in the same way that tags/ID are. This could be useful to better display GOTY editions of games with extremely long titles (name with GOTY subtitle in game list, normal name once mounted). It doesn't necessarily have to be done using the SUB_TITLE parameter (since editing the PARAM.SFO manually to include one would be a pain with the offsets and everything, though I might be willing to write a tool to do it automatically as programming practice if this feature does get added), subtitles or whatever else you wanted to display could be written to a text file along with the ID and game/disc version of the game where you wanted to display them (like what is done with favorites).

What do you think Aldo?

**Comment by aldostools** [comment]
To include the version in the game list is harder to acquire and requires much more processing due there are more conditions, like if the game has update there are 2 PARAM.SFO that must be checked. If the ISO doesn't have an external PARAM.SFO it also requires extra processing.

Download [webftp_server.zip](https://github.com/aldostools/webMAN-MOD/files/6760140/webftp_server.zip)

Instead I implemented a way to show the Title ID, Version, Title of the game currently mounted and the path of the last mounted game pressing **R2+O**

R2+O is used also to show the current IDPS and to cancel the background copy and game firmware version fix.

You can check if this feature helps with your need. I will release the new build as an update package later in the day.

**Comment by ghost** [comment]
You're right, I didn't consider that there could be updates present for any given game (I was only thinking of the ISO). Though, maybe being able to display disc version might be worth it? (For games like MGS4 which had a 2.00 re-release with trophy support). I guess it would only require modifying the parse_paramsfo function to also look for disc version, and passing the value to display (I don't remember exactly what disc version is called exactly in the param.sfo). Though, if it adds too much processing to wMM as well, it might not be worth it. (I'm guessing displaying custom text would also require much more processing and ram).

The new feature you added is indeed useful, since it's a quick way to get the game version from XMB. Thanks!

**Comment by aldostools** [comment]
I have updated the plugin with a new option in /setup.ps3 to show the game version along with the tags/ID

![image](https://user-images.githubusercontent.com/974897/124397161-4399c980-dcdc-11eb-96c4-df507bbcc4a3.png)

So now there are 2 ways to see the game version: R2+O or including the Version the "Info" subtitle of the XMB game list

You can get the new build from the release page or breowlogy or through the online update in webMAN menu.

**Comment by ghost** [comment]
Amazing work Aldo! I absolutely love it. I assume this is the APP_VERSION parameter in the param.sfo? I just checked the PS3 dev wiki and indeed there are a few older games that do not include it, so it was nice to know you found a workaround/compromise.

By the way, what I meant by disc version was the VERSION parameter in the SFO, which is supposedly always in the param.sfo of disc games and is used to differentiate different re-releases (like GOTY, with trophy support, etc). Or is this what you're displaying in XMB?

**Comment by aldostools** [comment]
The field displayed from PARAM.SFO is APP_VER

When the option is selected, the APP_VER is first obtained from the PARAM.SFO in PS3_GAME foder for the JB games or from /dev_hdd0/tmp/wmtmp for ISO (net/ntfs/exfat). If the PARAM.SFO is not found the APP_VER is not shown.

Once the APP_VER is obtained. The plugin checks if there is an APP_VER in /dev_hdd0/game/TITLE_ID/PARAM.SFO
If there is one, this is the one displayed in the game list.

The reason why I also check the APP_VER in /dev_hdd0/game is because that is the real version used when the game is launched. Anyway the APP_VER in the disc (with rare exceptions) usually is 1.00 or 1.01, so it would not be useful.

You still can see the disc version if you open the File Manager throught the web brower and naviage to /dev_bdvd/PS3_GAME

**Comment by ghost** [comment]
Alright, thanks again Aldo! It's a great feature. I'm guessing that unchecking PARAM.SFO in settings would result in no APP_VER being shown, right? (I've never really understood how that option worked). This is my last question, and the feature has been implemented, so feel free to close the issue with your next reply.

**Comment by aldostools** [comment]
The option "PARAM.SFO" in /setup.ps3 actually updates the setting: webman_config->use_filename

In other words: when the option "PARAM.SFO" is checked, the **title of the game** is obtained from the PARAM.SFO.
When the option is unchecked, the game name is obtained from the folder name for JB games or the file name of the ISO.

So that option should not have an effect.
