### ISSUE TITLE
PSP Launchers Black Screen

### ISSUE THREAD

**Issue by OldGnashburg** [aldostools/webMAN-MOD#543]
So the PSP Launchers included with the last 2 versions of Webman are broken, I kept getting a black screen upon booting any game, hard crash, had to force shutdown. After trying everything else, using an old, outdated Launcher from 2013 by someone named jikyuu fixed it. I don't know if other people are having issues but it would be good to look into.

**Comment by aldostools** [comment]
The PSP Launchers included in webMAN MOD release page are intended to be used with webMAN MOD.
These launchers don't include the file lambda.db that  is checked by the official Cobra API, but webMAN MOD uses a custom API that ignores that file.

lambda.db is an encrypted file containing the psp emulator from FW 4.00. They were required by CFW 3.55 to improve the compatibility of certain games. But that file is not longer needed in 4.x

Backup managers like multiMAN or IRISMAN use the official Cobra API. Therefore lambda.db is checked.

**Comment by OldGnashburg** [comment]
So why do I get a black screen when mounting and launching with Webman Mod? Is it a Cobra issue or a Webman Mod issue? I have this issue on 4.84.2 Rebug REX, 4.88.1 Evilnat, 4.88.2 Evilnat Beta. I've reinstalled OFW and then reinstalled Rebug, and Evilnat multiple times, with nothing, reformatted the HDD, rebuilt file system everything. I'd prefer to use the Webman Mod releases but they just crash for me. Using the other ones were the only way to avoid the crash. 

If it's relevant I am using a CECHA01.

**Comment by aldostools** [comment]
Thank you for your feedback. It looks like the last time I repacked the PSP Launchers, I used the wrong version.

Today I repacked the PSP Launchers with right version and tested them on Evilnat 4.88.2 with Cobra 8.3 & Mamba 8.4. They should work fine on all other CFWs including Rebug 4.84.2, 4.85.1 and 4.86.1

You can download the updated PSP launchers from:
https://github.com/aldostools/webMAN-MOD/releases/tag/1.47.36
https://store.brewology.com/ahomebrew.php?brewid=310

They are the PSP Launchers fixed by jjkkyu relesed on 12/13/13, with lambda.db removed and updated icons.

**Comment by OldGnashburg** [comment]
Launcher works now. Thanks closing issue.
