### ISSUE TITLE
webMAN Installed on CFW crashes HEN

### ISSUE THREAD

**Issue by PS3-Pro** [aldostools/webMAN-MOD#582]
I always switch between CFW and HFW

When I install webMAN MOD while in CFW and go back to HFW, it prevents HEN from being enabled, hanging on the ENABLING HEN screen.

I know how to solve it, but why it happens?

My mod includes webMAN MOD because of its dependencies, I always have to install HFW and then install HEN and FTP the sprx to my installer, so this way webMAN MOD works on both CFW / HFW, is there any downside in doing that?

**Comment by aldostools** [comment]
webMAN MOD is loaded by Cobra payload (or HEN payload). If you installed the plugin in CFW, when you returned to HFW the plugin is not loaded in memory. Therefore it should not prevent HEN from being enabled.

I recommend to check "Disable content scan on startup", because it consumes a great amount of memory when the plugin is loaded and could interfere with other processes that also demand memory.

If the plugin works fine after transferring it through FTP, there shouldn't be any downside. Just make sure that all the dependency files are present. It should work without them, but there will be limited functionalities.

**Comment by PS3-Pro** [comment]
Yeap, i always notice that when it happens, the led gets stuck blinking in yellow until the system completly freezes. Some users gets this issue when install my mod, i'll make a boot_init to disable the automatic scan to prevent it.

Thanks aldo.
