### ISSUE TITLE
PS3 freezes when trying to launch games

### ISSUE THREAD

**Issue by deadpahn** [aldostools/webMAN-MOD#630]
Noticed that the webserver isn't running. When I try to launch the setup the browser is trying http//0/setup.ps3

I'm guessing that something isn't running correctly or perhaps if the webserver needs to be running in order to launch games. Mangaguns mounts and plays games fine.

Not sure what I did exactly, was working fine a couple of days ago. I did try to rip a new game I got from ebay (Resonance of fate) and it was giving me a lot of drama when I was trying to mount that and rip via multiman. Maybe that game installed something that broken webman? 

I tried to reinstall webman but it's still won't work. I'm not sure where the error log is or how I could find it since the webserver is not working. 

While writing this report I noticed that the logo is the ps3 logo and not cobra. I think my game might of install the official firmware ? 

I'll try to reinstall

**Comment by deadpahn** [comment]
ok, so I installed [CFW EVILNAT 4.88.2 COBRA 8.3 and it works now. I guess it always was the PS3 logo anyway (must of been thinking of another CFW) but my guess is that game I tried to rip might of installed some stuff that broke the CFW. First thing I did was look to see if the setup link works. It shows up (IP still 0 though... I thought it would be something else). It mounted a ps1 game just fine and is booting it.

You can close this ticket but it might be helpful for people searching as I didn't find any threads searching with my ps3s symptoms.

Thanks for some great software :)

**Comment by aldostools** [comment]
I'm glad that you could fix the issue after reinstall CFW Evilnat 4.88.2

It looks your CFW entered to non-Cobra mode. In this mode the /boot_plugins_nocobra.txt to load different plugins.
ManaGunZ works fine because it loads Mamba which is a payload similar to Cobra that allows to load ISOs.

If you get the same issue again, check if your CFW is in non-Cobra mode before proceed to reinstall the PUP again.
It is faster to switch the mode than reinstall all the system files.
