### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by LouisGarry** [aldostools/webMAN-MOD#640]
Hello Aldo, under the ROMS folder (ROM format games) , can you add the total number of existing roms?

Thank you.

**Comment by aldostools** [comment]
It already shows the total number of ROMs per category:
![image](https://user-images.githubusercontent.com/974897/159845554-a056faaa-b231-4e29-9c24-1dcba8550aae.png)

If you mean the total of ROMS for all sub-categories, that would require to change the logic of how the content is scanned. The attribute table for ROMS folder is generated before the ROMS are scanned and the total number of roms is unknown at this point.

The current logic is very complex because the ROMs scanning was not designed from the begining and the way that I managed to add them requires to re-run the scanning several times. In short, it's a headache.

**Comment by aldostools** [comment]
After some deeper analysis I managed to find a solution using a dirty hack 🤣 

When the attribute table for the ROMS folder is created, now I create an empty placeholder filled with spaces.
After all ROMS have been scanned, I compute the total and inject the value in the placeholder.

It's not elegant, but it does the job 😄 You can update or re-download the installer from the release page.

**Comment by LouisGarry** [comment]
Thanks Aldo, 
But, error compile if commented #define USE_NTFS
