### ISSUE TITLE
About the same game

### ISSUE THREAD

**Issue by LouisGarry** [aldostools/webMAN-MOD#657]
Hi Aldo, there is a report in my community that if there is a game on the internal HDD that is the same as the FAT32 USB Drive, webMAN Games does not display the games (GAMES/PS3ISO) from usb.

For example, in /dev_hdd0 and a FAT32 USB Drive there is wwe.iso, which appears in webMAN Games only games from hdd0.

I don't know if it happens on NTFS/exFAT USB Drives too.
thanks.

**Comment by LouisGarry** [comment]
And 1 more report, Blu-Ray and DVD showing double pkg.
The pkg file is in the packages folder exFAT USB Drive and uses the latest prepISO 1.29.

Thanks.

**Comment by aldostools** [comment]
webMAN MOD checks if the games were already listed from the internal HDD and ignores these games.
This is intentional to avoid clutter the list with duplicated entries from other devices (FAT32, exFAT/NTFS or NET).

About the duplicated packages, I have to investigate. It could be due prepISO 1.29 includes the file extension in the cache file, but 1.28 doesn't.

Try disabling /dev_ntfs in /setup.ps3 and clean /dev_hdd0/tmp/wmtmp

Or re-download and install the lastest binaries of prepISO 1.29 and use it with wMM 1.47.39.

If I find some bug I will release a fix as usual.
