### ISSUE TITLE
Webman Mod 1.47.40 NTFS Not Working 

### ISSUE THREAD

**Issue by GanGstaOne** [aldostools/webMAN-MOD#688]
NTFS drive not working in Webman Mod 1.47.40 no matter how many times i try i even tried different PrepIso versions it just doesn't work but it works fine in Webman Mod 1.47.39 and older versions PLEASE FIX
using Rebug 4.84.2 CEX

**Comment by GanGstaOne** [comment]
after reverting Back to 1.47.39 and then updating from within webman mod to 1.47.40 now works need to test if it will detect new games added to the NTFS drive

EDIT: No it doesn't work it only showed thr games after updating from 1.47.39 but when i unplug the drive then plug it back in it Dosn't work Please fix

**Comment by PS3-Pro** [comment]
Some friends of mine confirmed it too. not even PrepISO is listing the games.

**Comment by GanGstaOne** [comment]
i tried it on 2 different slim and still not working guess what ever aldo changed between 39 and 40 is the issue cause he did said there were alot under the hood changes
hope he fixes it

**Comment by aldostools** [comment]
Thank you for your report. I'm investigating.

**Comment by GanGstaOne** [comment]
theres something else when i used boot mamba pkg to run Mamba 8.4 i can't install single pkg from any source tried several usb sticks internal hdd nothing works don't know if this is right never used mamba before i switched back to cobra and the issue is gone

**Comment by aldostools** [comment]
> theres something else when i used boot mamba pkg to run Mamba 8.4 i can't install single pkg from any source tried several usb sticks internal hdd nothing works don't know if this is right never used mamba before i switched back to cobra and the issue is gone

The issue about NTFS items not being listed has been fixed in the latest commit.
Please use the online updater or re-download the installer from [releases](https://github.com/aldostools/webMAN-MOD/releases) and install the new build.

About MAMBA 8.4. I just tested MAMBA 8.4 on my console with CFW Evilnat 4.88.2.
I disabled Cobra and rebooted. I could install the single packages without issues.

Please check if the downloaded pkg is corrupted. Try a different one or re-downloaded the pkg.
