### ISSUE TITLE
being able to sign into PSN without clearing syscals after using multiman

### ISSUE THREAD

**Issue by illusionalDEX** [aldostools/webMAN-MOD#695]

**Comment by aldostools** [comment]
I just tested the function in wMM 1.47.41 and the Sign in option appears blocked after return from multiMAN.

multiMAN / IRISMAN removes all the mappings when they start. 

webMAN poll thread monitors the syscalls and replies the mappings every 3 seconds (except when you're scanning for content that continues polling when the scan complete).

Could you provide more details of the exact procedure to reproduce the bug?

**Comment by illusionalDEX** [comment]
i would just open multiman then close it with the quit option in the app... then try to sign into psn and itll let me do it.

**Comment by aldostools** [comment]
That is what I did. Try using the online updater and reboot after update.

Maybe you tried to access the PSN too fast.

**Comment by illusionalDEX** [comment]
i updated webman to latest. reset. checked the sign-in screen if it says if i had to clear syscalls and i do... then i went into multiman (4.85.1) then closed it... i can now sign-in even when i wait a min... i also tried using rebug toolbox to see if it does the same thing (it doesnt)

**Comment by aldostools** [comment]
Rebug Toolbox doesn't remove the sys_map_paths. It is multiMAN that does it. 

The issue really is on multiMAN's side, I just try to fix it.

If I'm correct, if it allows to login, also the webMAN menu should freeze your system because the mapping to wm_proxy is also removed by multiMAN.

The sys_map_paths seems to be working fine on my system.
