### ISSUE TITLE
[Question] How to use PARAM.SFO view?

### ISSUE THREAD

**Issue by PS3-Pro** [aldostools/webMAN-MOD#696]
̶I̶ ̶j̶u̶s̶t̶ ̶s̶a̶w̶ ̶t̶h̶i̶s̶ ̶n̶e̶w̶ ̶f̶e̶a̶t̶u̶r̶e̶
̶-̶A̶d̶d̶e̶d̶ ̶l̶i̶n̶k̶ ̶t̶o̶ ̶/̶v̶i̶e̶w̶.̶p̶s̶3̶ ̶f̶o̶r̶ ̶.̶S̶F̶O̶ ̶f̶i̶l̶e̶s̶ ̶i̶n̶ ̶F̶i̶l̶e̶ ̶M̶a̶n̶a̶g̶e̶r̶.̶
̶
̶B̶u̶t̶ ̶i̶ ̶c̶o̶u̶l̶d̶n̶'̶t̶ ̶m̶a̶k̶e̶ ̶i̶t̶ ̶w̶o̶r̶k̶

EDIT: Seems like some of my files were old lol , i just installed the FULL pkg and now it works.

Aldo is possible to view .xml and .txt files via the file manager and edit them on the fly? would be nice for boot_plugins.txt, webman scripts and system xmls edits, without extra software.

![image](https://user-images.githubusercontent.com/74815634/166523376-77313fb6-6cd1-44e6-9308-f87c732db946.png)
![image](https://user-images.githubusercontent.com/74815634/166523421-474bd09f-a669-40de-bbab-24249ad5602a.png)

**Comment by aldostools** [comment]
Obviously it will not work if you're using version 1.47.37.

Try with latest build 1.47.41

**Comment by aldostools** [comment]
It is possible to edit XML and TXT using the web command /edit.ps3&lt;path-of-text-file>

However the text file cannot be larger than 1.2KB. The reason is that the text is passed through the URL and there is a limitation in the size of the URL.

The command is ideal to edit boot_plugins.txt on the PS3 since these files usually are smaller than 1KB.
