### ISSUE TITLE
FPS Counter temperature display

### ISSUE THREAD

**Issue by Ang3l42** [aldostools/webMAN-MOD#713]
Updated webman mod today and temperatureType: CELSIUS or temperatureType: FAHRENHEIT not working. Temperature is always shown in BOTH. 
CPU and GPU temperatures are shown in two lines. It was more convenient when they were shown in one line through /

**Comment by aldostools** [comment]
Thank you for bug report. I confirmed the bug.

I will notify @TheRouletteBoi who is the maintainer of VshFpsPlugin.

**Comment by aldostools** [comment]
The issue was fixed by TheRouletteBoi. A new build of VshFpsCounter.sprx is now included in webMAN MOD.

Update to the latest build using the online updater in webMAN Games > webMAN Setup menu or re-download the installer from  breowlogy or [releases](https://github.com/aldostools/webMAN-MOD/releses)
