### ISSUE TITLE
CCAPI/TMAPI doesn't works

### ISSUE THREAD

**Issue by Elenimotoon** [aldostools/webMAN-MOD#716]
At the latest release, the CCAPI/TMAPI doesn't works, it shows you that your computer tool is connected, but in game the changes that you made with PC doesn't appears, in other updates yes but not in this one. 

Maybe it's an error from latest Hen version or 4.89 HFW but I'm not sure. 

Tested in a Hen console with a previous factory reset in it, installed Webman as "first time".

**Comment by aldostools** [comment]
Please test CCAPI/TMAPI uninstalling webMAN MOD. The plugin is needed only for PS3MAPI.

If the issue still occurs also with webMAN MOD uninstalled, then it can be an issue with the latest release of HEN.
If the issue is solved with webMAN MOD uninstalled, then I will need the exact steps to reproduce the issue.

**Comment by Elenimotoon** [comment]
I'll test it out later then, thanks!

**Comment by Elenimotoon** [comment]
Hi, confirmed that issue is from Hen and not from Webman mod

Have a nice day and sorry for the inconvenience.
