### ISSUE TITLE
Not showing all PKG files in Blu-ray and DVD folder

### ISSUE THREAD

**Issue by Walter-Correa** [aldostools/webMAN-MOD#735]
As the title already says, it is not showing all the PKG files in the Blu-ray and DVD folder.
**I already tried to reinstall Webman but it didn't work!**

**There are 14 games in the PKG folder of my external HD:**
![screenshot_2022_07_02_17_22_55](https://user-images.githubusercontent.com/20175176/177015417-e5695e05-8474-44cc-ad92-fbe9bb6a4c9a.jpg)

**But it's only showing 10 in the XMB (Blu-ray and DVD), even after using prepISO:**
![screenshot_2022_07_02_17_21_23](https://user-images.githubusercontent.com/20175176/177015379-44ac0b5a-b7f9-405a-a87c-6daccac83ff7.jpg)

**Comment by aldostools** [comment]
Please, first check if the cache file .ntfs[BDFILE] was created in /dev_hdd0/tmp/wmtmp

If they weren't created, try moving all the packages to another folder (e.g. TEST) and leave only the 4 ones that weren't listed in PKG. Then run prepISO again.

I suspect that they were not listed because the files could be too fragmented. You can try to defrag the HDD on the PC.

If they were created in /dev_hdd0/tmp/wmtmp but not listed on XMB, then the issue could be related to memory usage.
This normally can be solved changing the memory profile in /setup or selecting 4-bg in the option [MC 3072KB]

**Comment by Walter-Correa** [comment]
> 

After 1000 hours of defragmenting I come here to thank you, because that's exactly what solved the problem!
Thank you so much!
