### ISSUE TITLE
Artemis Engine Pop-up not working

### ISSUE THREAD

**Issue by PS3-Pro** [aldostools/webMAN-MOD#740]
Aldo, the webman's artemis patching engine is no longer displaying the pop up notification when launching a game

**Comment by aldostools** [comment]
If the notification is not showing is because the Artemis patch engine in wMM is not starting automatically.

1, Make sure that Artemis option is checked in /setup.ps3
2. Make sure that the patch file `/dev_hdd0/tmp/arts.txt` exists
3. Make sure that you're running Lite edition or Full edition. The standard edition does not support Artemis.

The file `arts.txt` is deleted when you exit from the game or when you mount a new game.
If you returned to XMB and launched the game again without launch Artemis or if you mounted the game after launch Artemis, the file will be deleted and the patch engine will not be launched automatically.

You can launch it manually using http://ps3-ip-address/artemis.ps3 from a PC, tablet or cellphone.

I confirmed that the feature is working in the latest build of webMAN MOD 1.47.42.

**Comment by PS3-Pro** [comment]
silly mistake, thanks

At the time I tested it, the art.txt was not deleted when exiting the game, much better now.
