### ISSUE TITLE
PS3NetSRV - 20220421 - Error on Linux

### ISSUE THREAD

**Issue by wes1993** [aldostools/webMAN-MOD#743]
Hello,
i have upgraded the ps3netsrv but there is a Bug and won't start unfortunately:
![image](https://user-images.githubusercontent.com/52070589/179318607-57cae79d-c20f-4f88-9839-6c4704e7947b.png)

With the old version (20220301) works.

Best Regards
Stefano

**Comment by aldostools** [comment]
Thank you for your feedback.

Could you provide more details about the error? 
For instance, when do you get the error? Compiling the code, starting the program? listing a directory? mounting a game?

Could you provide the exact source code that you used to compile the project and the resulting binary?

In your image, it mentions '&lt;!DOCTYPE html>' but this program does not use HTML code.
Only LICENSE.TXT, README.md and aes.c make reference to a html link as a comment.

I suspect that you downloaded the HTML page from github, instead of the RAW file.

Alternatively you can try the binaries compiled by JCorrêa for 32 platforms:
https://github.com/jhonathanc/ps3netsrv/releases/tag/20220421

The main differences between 20220421 and 20220301 are:
- BUFFER_SIZE in 20220421 is 4MB like original project. In 20220301 was 3MB, but multiMAN expects 4MB.
- 20220421 print on console more debug errors
- 20220421 allows recursive directory scanning

None of these changes look related to the error reported in your screenshot.

**Comment by wes1993** [comment]
Sorry @aldostools ,
My bad, i hav downloaded incorrect file :-(

Best Regards
Stefano
