### ISSUE TITLE
webman crashes my hen please help

### ISSUE THREAD

**Issue by amine08dev** [aldostools/webMAN-MOD#748]
please I have a big problem here 
after I install webman my ps3 did restart and after enablehen it didn't close automatically 
so I close it manually and the screen appears with the wallpaper only and I need to close my ps3
I forgot to say that a yellow and green flash appears
I wanna uninstall webman without enablehen how can I do it
HELP MEEEE

NOTE :
.this problem was in my ps3 before and I solve it by formatting the hard disk and never installing WM
.sorry for the bad English
.MY system is 4.75 slim

**Comment by aldostools** [comment]
The yellow/greesh leds means that webMAN is scanning the contents in the attached disks.

You can try the following:
1- Disconnect all USB drives and wait until webMAN finishes the scanning.

OR
2- Create an empty file named **boot_plugins.txt** in the root of your USB device formatted in FAT32 MBR and plug it in /dev_usb000.

This file of 0 bytes will be used instead of the internal /dev_hdd0/boot_plugins.txt preventing that webMAN MOD is loaded

3- If you have the XMB File Explorer installed, you can delete /dev_hdd0/boot_plugins.txt from XMB

Once HEN is enabled without freeze you can use multiMAN or IRISMAN to delete at least the following files:
/dev_hdd0/boot_plugins.txt
/dev_hdd0/plugins/webftp_server.sprx
/dev_hdd0/tmp/wm_config.bin
/dev_hdd0/tmp/wm_icons
/dev_hdd0/tmp/wm_lang
/dev_hdd0/tmp/wm_res
/dev_hdd0/tmp/wmtmp

**Comment by amine08dev** [comment]
h

**Comment by aldostools** [comment]
Then create the empty boot_plugins.txt in USB.

**Comment by amine08dev** [comment]
thanks a lot you save me
ur the best
