### ISSUE TITLE
Subfolders not appearing upon opening, "webMAN Games"

### ISSUE THREAD

**Issue by mariemoo** [aldostools/webMAN-MOD#756]
As the title states, I am incapable of accessing the subfolders for PS3, PS2, PS1, PSP, DVD & BD and ROMS as they are not being displayed. I am running PS3HEN 3.1.1 along with version 1.47.42 of webMAN-MOD. I currently do not have any other plugins installed other than, "Prepare NTFS Drives for webMAN" and, "PKGi PS3." Forgive me if may have forgotten any other important details, this is my first time ever using Github's issue creation tool. Thank you for reading.

**Comment by aldostools** [comment]
Try disconnecting all USB drives and run prepISO.

It should return to XMB and scan only the content in the internal HDD. Wait about 1 minute and check if the folders are listed.

If they don't show, it could be that some game in the internal HDD is breaking the XML.

If they show, then the issue is in the external HDD. Maybe too much games or a bad file name.

Also try deleting /dev_hdd0/tmp/wm_config.bin and reboot. This reset the settings to the default configuration of webMAN MOD.

**Comment by mariemoo** [comment]
Thank you so much, I finally got the subfolders to appear. I really appreciate your help, good luck with the other releases

**Comment by aldostools** [comment]
Great!
