### ISSUE TITLE
webMAN-MOD lite freezes PS3 on ISO mount

### ISSUE THREAD

**Issue by mkardi** [aldostools/webMAN-MOD#839]
I have PS3 slim with cfw 4.90 evilnat 8.4 installed
I also installed webMAN-MOD lite edition 1.47.44

Issue: whenever I attempt to mount any PS3, PS2 or PS1 ISO then PS3 will freeze with blinking power light.

This does not seem to happen with standard edition, only with lite.
Does not matter if game ISOs are stored in internal hdd0 or external USB drive (fat32, exfat, ntfs)

Is there any advice how to fix it?

**Comment by aldostools** [comment]
Thank you for the bug report. The issue was caused by an incorrect compilation flag that prevented some LV2 patches when Lite edition was used.

Please use the online updater or download the installer and re-install again. I sincerely apologize for the inconveniences.
https://github.com/aldostools/webMAN-MOD/releases

**Comment by mkardi** [comment]
I confirm latest version fixed mounting issue.

**Comment by josete2k** [comment]
I have same issue with lite and full of the last version.

Ps3 freezing When scanning ntfs drive and Led blinking.

Slim PS3 with Evilnat 4.90.

This drive was working in a backwards Ps3 and 4.88 CFW.


Irisman and multiman are working as well.
