### ISSUE TITLE
[feature-request] custom mount paths

### ISSUE THREAD

**Issue by ghost** [aldostools/webMAN-MOD#843]
Hi @aldostools, I am wondering if it's possible to leverage netiso against local mount points? My use case would be something along the lines of I might use another emulation tool like RetroArch elsewhere on my network, but I would like to point a local mount point pointing to something made available via netiso.

i.e /net1/ROMS/saves (retroarch saves) -> /dev_hdd0/retroarch/saves

I don't know about the VMC save format so I don't know if it's cross compatible with other emulators, but that is the use case I am looking for, the ability to make save data available automatically via mounting a netiso connection.

**Comment by aldostools** [comment]
In order to access the content of a remote folder it first must be mounted.

Once you have mounted /net1/ROMS/saves as /dev_bdvd, you can use:
/remap.ps3/dev_hdd0/retroarch/saves&to=/dev_bdvd

The remote content is read-only. However I don't think that would work for you, because saves also have to be written.

**Comment by ghost** [comment]
Ah I hadn't looked at using remap, but that could be because I misunderstood the mapping in the web frontend.

Read only gives me enough to play and experiment with. Thanks for the reply ☺️
