### ISSUE TITLE
[Question] On hardware ps2 compatible superslims

### ISSUE THREAD

**Issue by robokingscosmosps3** [aldostools/webMAN-MOD#866]
What can homebrew do if later ps3s can be hard modded for full ps2 support? will they still support bin.enc or will .iso become possible due to this discovery?

**Comment by aldostools** [comment]
As far as I know, the scenario that you comment is speculation.

Only the PS3 phat models CECHA/CECHB have full PS2 backwards compatibility. They have physical emotion engine (EE) + Graphics Synthesizer (GS) hardware. In other words, they come with a physical PS2 embedded into the PS3.

Leter phat models CECHC/CECHE have semi-full PS2 backwards compatibility. They have a physical Graphics Synthesizer (GS) hardware. The emotion engine (EE) is emulated by software.

All other models, including all slims & superslims, use PS2 software emulation via ps2_netemu.

Encrypted bin.enc is supported on all PS3 models. They are the official PS2 Classics format from PSN store.

Non-encrypted PS2 ISO are supported only on PS3 models that are CFW capable.

HEN doesn't support PS2 ISO because the LV2 kernel and all the patches are removed from memory when the PS2 emulator is loaded. Therefore it is not possible to use a payload to add ISO support. The only way to load PS2 games on HEN is using the official method via PS2 Classics.
