### ISSUE TITLE
No content in /net1-4, ONLY /net0 can be uesd

### ISSUE THREAD

**Issue by palBazzi** [aldostools/webMAN-MOD#874]
Hi man,
My PS3's wMan version is 1.47.44, and I have set two PS3netsrv servers in “Setup”.
But ONLY content in /net0 can be displayed(or accessed), no content in /net1-4 even the setting is copied from /net0.
console log on /net1-4's server also have no variation when PS3 trying to access them.(Is that means PS3 never started the process to connect /net1-4?)
I must change /net1(1-4 I have tried)'s setting to /net0 then PS3 can access it.
So, I can't access two(or more) PS3netsrv servers in the same time.

**Comment by aldostools** [comment]
Thank you for the bug report. I'm checking now.

**Comment by aldostools** [comment]
I've checked your issue. The reason that you cannot access net1-net4 is a validation for duplicated host+port.

If run multiple servers on the same IP addresses, you must assign a different port number to each server. The default is 38008

![image](https://user-images.githubusercontent.com/974897/235554690-7f50e1c2-29e1-4369-862b-464f1227d4f6.png)

In the example above, the servers /net0 (PS3NETSRV#1) and /net1 (PS3NETSRV#2) are visible. But net3-net4 are blocked, because they are already configured in /net0

The reason of this check for Host+IP is because if you have defined the same server multiple times, webMAN would list the content on these servers duplicated (or more times).

**Comment by palBazzi** [comment]
Thanks for reply.
Sorry for forgetting to describe my environment.
I have 2 PS3netsrv Instances on my NAS(2 IPs, IPa=192.168.0.a, IPb=192.168.0.b), port from 38008 to 38009, one for PS3 games the other for PS2/1 games(on different disk). All of them can be accessed when configured in /net0.
Configuration combinations have tested:
/net0 (PS3NETSRV#1)->[NAS IPa]:38008
/net1 (PS3NETSRV#2)->[NAS IPa]:38009(no content)

/net0 (PS3NETSRV#1)->[NAS IPa]:38009
/net1 (PS3NETSRV#2)->[NAS IPa]:38008(no content)

/net0 (PS3NETSRV#1)->[NAS IPb]:38009
/net1 (PS3NETSRV#2)->[NAS IPa]:38008(no content)

/net0 (PS3NETSRV#1)->[NAS IPa]:38009
/net1 (PS3NETSRV#2)->[NAS IPb]:38008(no content)

/net0 (PS3NETSRV#1)->[NAS IPb]:38008
/net1 (PS3NETSRV#2)->[NAS IPa]:38009(no content)
/net2 (PS3NETSRV#3)->[NAS IPa]:38008(no content)
/net3 (PS3NETSRV#4)->[NAS IPb]:38010(38010 is a redirection port to 38008 by NAS's firewall, no content)

**Comment by aldostools** [comment]
In that case I don't know what's wrong in your setup, it worked fine on my tests today.

You could try running only one instance of ps3netsrv and use the [virtual linked directories](https://github.com/aldostools/webMAN-MOD/wiki/~-PS3-NET-Server#virtual-linked-directories) to access the remote content as part of the local folders.

Example: create a text file named PS3ISO.INI, list the remote path or other local paths inside PS3ISO folder:
````
\\192.168.1.150\SHARED\PS3ISO
/mount/c/other/path/PS3ISO

**Comment by palBazzi** [comment]
Thanks. I will try virtual linked directories later.
Started a new ps3netsrv instance on my PC a moment ago. It still can only be accessed when configure to /net0.
The log seems to show PS3 never start the connection to /net1-4. Because it always "waiting client" until using "telnet PC's IP 38008" test it.

**Comment by palBazzi** [comment]
Works fine after removing and reinstalling webMan.
