### ISSUE TITLE
[Quick Question] PS2 Supported formats

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#903]
Aldo the wiki says that only .iso and bin.enc ps2 games are supported, i got a ps2 game in .bin format and webman loaded it just fine,

Does webman supports this format or maybe it is not a bin but a iso renamed?

**Comment by aldostools** [comment]
Indeed the following file extensions are detected as ISO:
- .iso / .ISO
- .iso.0 / .ISO.0
- .BIN.ENC
- .bin / .BIN
- .img / .IMG
- .mdf / .MDF

PS1 games need also a .ccd or .cue file

**Comment by LuanTeles** [comment]
@aldostools i read that ps2 games under 700 MB can be in a bin + cue format, is that right? webman will mount it ?

Also, if a ps3/ps2/ps1/psp backups are in any of these img formats

.iso / .ISO
.iso.0 / .ISO.0
.BIN.ENC
.bin / .BIN
.img / .IMG
.mdf / .MDF

they'll play? i'm asking those question because i'm updating my guides and the xml that lists the games and files for uninstall

**Comment by aldostools** [comment]
> i read that ps2 games under 700 MB can be in a bin + cue format, is that right? webman will mount it ?

PS2 games can be CD or DVD. Indeed the blue icon are for PS2 CD and the yellow icon for PS2 DVD.

If I recall correctly, at some point webMAN MOD used the image size to detect the CD. Now it reads the sectors.

Cobra/Mamba/HEN payload check the sector 0x10 (offset 0x8000). If it has "CD001" it assumes DVD sectors of 2048 bytes. Otherwise the ISO is processed as a CD.

The module `common.c` of ps2emu payload handles CD sectors of 2048, 2328, 2340, 2352, 2364 and DVD sectors of 2048 and 2064 bytes.

> Also, if a ps3/ps2/ps1/psp baclup are in any of these img formats they'll play?

In theory, they should work. Although some features may consider only .ISO / .ISO.0 or .CUE/.BIN for PSX.

**Comment by LuanTeles** [comment]
thanks for the info
