### ISSUE TITLE
ISOs inside PS3ISO on internal HDD not working

### ISSUE THREAD

**Issue by superwave1999** [aldostools/webMAN-MOD#918]
Excuse my lack of understanding since i've only been invested in the "free" (as in freedom) PS3 scene for a short while.

I have a PS3 Super Slim - BT and BD are confirmed working.

I have installed HEN from a quick format HDD (brand new 500gb) starting at the 4.90 OFW, then 4.90 HFW, and then installed webMAN from the PKG.

All settings are default, no PSN account associated, and I tried to run a backup of Sonic Unleashed (EU) that is also confirmed working on a friends PS3 FAT with CFW (up to date webman).

Mounting the ISO to app_home a.k.a "inserting the disk" works fine, but when I run the game, I either get a 80010017 error or the game black-screens. (Yes, I made sure to enable HEN beforehand)

I updated the game to the latest version, and this time a loading indicator appears on screen, but stays there to infinity.

From what I can guess, the "disk" mounted at app_home isn't being accessed by the system, but since the "EXE" has been updated, the loading indicator manages to appear.

I have tried other backups such as BLUR and Uncharted 3, and the same issue persists.

Should I try to run a full-format of the HDD? I can provide my exact superslim model if necessary.

**Comment by aldostools** [comment]
Error 0x80010017 = Failure in authorizing SELF. Program authentication fail (Error starting BluRay game). EAUTHFAIL

I suggest you that try playing the same ISOs with multiMAN or IRISMAN. 
* If the ISOs also fail with these backup managers, then the problem is a bad ISO or HEN payload.
* If the ISOs play fine, then I suggest you that use the latest build of webMAN MOD and test again
* If the problem persits in webMAN MOD, try installing the game update and test if it plays
* If the game still don't play, try converting the ISO to folder format and copy it to GAMES folder

**Comment by superwave1999** [comment]
After further investigation, it turns out the new HDD was faulty (probably knocked during transport) and corrupting data.

After confirming the ISO with the PS3 FAT and RPCS3, I replaced the hard drive with an older drive I had lying about and everything worked flawlessly.

Thanks for the help anyway!
