### ISSUE TITLE
VSH freezing

### ISSUE THREAD

**Issue by N2022062** [aldostools/webMAN-MOD#93]
1.47.05 or other version still have this problem
...
cant find why..

**Comment by N2022062** [comment]
1.when p3 start,u should press L2 R2 to start admin Every time?
2.should i copy /dev_hdd0/plugins/wm_vsh_menu.sprx to plugin.txt ？

**Comment by aldostools** [comment]
In 1.47.05, wm_vsh_menu.sprx and sLaunch.sprx are loaded dynamically from /dev_hdd0/tmp/wm_res
These plugins should be removed from boot_plugins.txt to save over 600KB of memory usage and prevent multiple issues caused by the reduced memory available in VSH.

Regarding the admin mode, try deleting the wm_config.bin and restart the system to use the default settings. By default the plugin operates in admin mode. The user mode is enabled when the combo ADMIN/USER MODE is turned on in /setup.ps3 under the section "XMB/In-Game PAD SHORTCUTS".

L2+R2+TRIANGLE is used to toggle admin/user mode the the combo is enabled.

**Comment by N2022062** [comment]
/dev_hdd0/tmp/wm_res/slaunch.sprx
/dev_hdd0/tmp/wm_res/wm_vsh_menu.sprx
i already put this above to "PS3MAPI --> VSH Plugins"
and saved.
when press select putton,it show "vsh unloaded",press select again,vsh still freeze...
i delete this version and ,install any old version,still has this problem,i cant understood why...

**Comment by N2022062** [comment]
i just find the bug!!!
if u use theme,and then press select,100% freeze.
DONT use any theme can show the VSH！

**Comment by aldostools** [comment]
Thank you for your feedback. It should be a bug in that theme that you were using.

I have used the plugin with different themes and I haven't experienced that error.

For instance, this is one of the themes that I frequently use on my PS3:
http://www.ps3-themes.com/gaming/ps4-xmb-2-0.html

**Comment by N2022062** [comment]
THX!I got it!
i'll try this theme .
