### ISSUE TITLE
PSP Launcher needs to renew license

### ISSUE THREAD

**Issue by alfredox123** [aldostools/webMAN-MOD#933]
Executing the psp launcher tells me to renew license, how to activate this app correctly? thank you for your time.

**Comment by alfredox123** [comment]
i tried installing PSP Launcher [Official by COBRA] | v2.0 since some people said it removes the license issue but im still having the same issue

**Comment by aldostools** [comment]
It could be due a corrupted RIF in exdata directory your current user. Try creating a new user and launch the PSP launcher from there.

**Comment by alfredox123** [comment]
can i fix the rif somehow? the thing is that if i create a new user i will lose all the rif ive already installed thhrough reactpsn (which are alot of dlcs) right? or im wrong here?

**Comment by aldostools** [comment]
You're wrong. The PS3 scan the license on all users.

Indeed the issue could happen also if you have a corrupted RIF in another user. 
I recommend to delete the RIF corresponding to your PSP launcher (there are various versions with different content ID).

**Comment by alfredox123** [comment]
I created a new user and still got the same license error, can you indicate what should I be looking for and which folder on my HDD?

**Comment by aldostools** [comment]
I haven't experienced that error. Try asking in PSX-PLACE forums. Maybe someone that had your same issue found a fix.

**Comment by alfredox123** [comment]
I created an account yesterday but I don't receive the confirmation email to confirm the account and start replying, the other users say that installing other launchers worked for them, I'm gonna try another to see if it does something

**Comment by alfredox123** [comment]
![IMG_20230822_142119](https://github.com/aldostools/webMAN-MOD/assets/13760359/733479fb-3e76-442e-9681-4df734bc5a70)
Tried all this with no success, there's a missing rap somewhere, maybe installing a game that use that same psp remaster launcher? Do you know any?

**Comment by aldostools** [comment]
I only use the PSP Launchers available in the release page of webMAN MOD:
https://github.com/aldostools/webMAN-MOD/releases

Maybe the issue is with PS3HEN, since I only use CFW and never have experieced this error.

By the way, the PSP launchers don't require a license due they are signed as npDRM free.

**Comment by alfredox123** [comment]
Yeah those are the ones I first tried, maybe is an issue with hen as you say, then I give up, thank you anyway

**Comment by TheSSJ** [comment]
Must be something with 4.90HFW 

Unfortunately i have no clue if and how to downgrade to prove this. Just saw a YouTube guide and the creator stated this as well

**Comment by Fls3h69** [comment]
Hey man alfredox I'm having exactly the problem you have and i kinda found out a better alternative and that is downloading psp games directly from the game stores or hen stores as pkg files , they run without needing the launcher

**Comment by Fls3h69** [comment]
Especially since psp games are a couple gig's or even by mb and i hope that helps

**Comment by LouisGarry** [comment]
> Maybe the issue is with PS3HEN

That's right, it's a bug from HEN 3.2.2, in 3.2.1 it works fine.

**Comment by aldostools** [comment]
> > Maybe the issue is with PS3HEN
> 
> That's right, it's a bug from HEN 3.2.2, in 3.2.1 it works fine.

Thank you @LouisGarry for your feedback.

@esc0rtd3w it seems the bug is due the last commit where we removed the variable is_psp_launcher that was used in HEN to make the code consistent with Cobra/Mamba payloads where it is not necessary:
-  Removed is_psp_launcher variable. It was creating an unnecessary the RAP for the PSP launcher

https://github.com/PS3Xploit/PS3HEN/commit/69805cad6c43330d01ad3e6a03f68e217728a237#diff-8936ac4e3f9327bde987df145f1e43ed54b014892aa10a0f581caa64e00670d2L1200-L1224

**Comment by LouisGarry** [comment]
Thank you Aldo, I also want to report, the last wMM commit does not display ROMS on webMAN Games, it is empty.

**Comment by aldostools** [comment]
Thank you. I will verify. I tested the ROMS a moment ago and they showed fine.

Are your ROMS in NTFS, FAT32, exFAT, NET or internal? I will test again with a clean setup.

**Comment by aldostools** [comment]
I tested again with a clean setup and the ROMS are listed/working properly. 
BTW My roms are in /dev_hdd0/ROMS
![image](https://github.com/aldostools/webMAN-MOD/assets/974897/a5efc2d6-e2c5-4e2b-9107-e26aa457f58d)

**Comment by LouisGarry** [comment]
> I tested again with a clean setup and the ROMS are listed/working properly. BTW My roms are in /dev_hdd0/ROMS ![image](https://private-user-images.githubusercontent.com/974897/309285499-a5efc2d6-e2c5-4e2b-9107-e26aa457f58d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMDI4MDgsIm5iZiI6MTcwOTMwMjUwOCwicGF0aCI6Ii85NzQ4OTcvMzA5Mjg1NDk5LWE1ZWZjMmQ2LWUyYzUtNGUyYi05MTA3LWUyNmFhNDU3ZjU4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQxNDE1MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjMzZTRkNjQ5ZDQzYjE3MzlmZjRiNGY2MGM2ZmMyNTZhMTA1YzBmMWZiZTY1ZWNmMjYwNWMxN2I5ZTkzZTU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P_2q6uTxfOZ-tSSp18-19hXINft129OT-i_hYAayMgE)

Thank you Aldo, that's strange, I'll try reinstalling wMM.

**Comment by aldostools** [comment]
I found the issue in games_xml.h. Please download again the latest build.

**Comment by LouisGarry** [comment]
Oh very fast, works great Aldo, thank you very much.

**Comment by aldostools** [comment]
Excelent. Thank you for your confirmation and the bug report.

**Comment by LouisGarry** [comment]
Hi Aldo, sorry to bother you again, can I ask to add a feature if a noBD is detected, mount the game folder auto focus to ☆app_home?  Thank You.

**Comment by aldostools** [comment]
> Hi Aldo, sorry to bother you again, can I ask to add a feature if a noBD is detected, mount the game folder auto focus to ☆app_home? Thank You.

Please download the latest build and test the requested feature. noBD patch must be checked in /setup.ps3

**Comment by LouisGarry** [comment]
Thank you Aldo, I'll try tomorrow

**Comment by LouisGarry** [comment]
Works great, thanks Aldo 🙏

**Comment by aldostools** [comment]
> Works great, thanks Aldo 🙏

Thank you for your feedback.

**Comment by LuanTeles** [comment]
@aldostools same issue on the latest hen (test 2) with your fix

Still asking for the license

**Comment by aldostools** [comment]
I checked the recent changes from my PR and the block of code related to RAP license for PSP Launcher is identical to the code used 2 years ago (3.1.1).

Therefore the bug should be caused by some other change in the payload. I recommend to make a test build replacing the whole `mappath.c` module using as base the one from 3.2.1 which is the last known version of PS3HEN without the issue is 3.2.1.

**Comment by aldostools** [comment]
@LuanTeles I checked mappath.c of 3.21 and the changes in the latest build are minimal and practically unrelated.

Is the clock of your PS3 updated? Are you using 4.90 or 4.91? It could be an issue with the symbols, but first need to know the version in use due the symbols are different in these 2 versions.

**Comment by LuanTeles** [comment]
I'm currently on version 4.91. Yeap, my clock is updated, I'll conduct further tests tonight and provide an update.

I consulted a friend who encountered a similar issue, and esc0 also confirmed the problem during their tests today.

Next, I plan to test version 3.2.1 of the hen, which is the last known version that worked without requiring a license.

Perhaps reorganizing the code could resolve the issue. When bucanero introduced the code to rename the act.dat file, it caused a malfunction with the reload categories feature. At that time, I simply moved it a few lines up, and the issue was resolved.

**Comment by LuanTeles** [comment]
@aldostools, I'm encountering the same issue with my PRO mod (on 4.90 CEX). Installing the license resolves it, but I suspect it's because my explorer_plugin.sprx offsets differ from Cobra's. I'm awaiting the new Cobra source release to address this. Could it be possible that the PSP offsets are incorrect? I haven't checked the explorer_plugin.sprx to compare the differences between version 4.89 and 4.91, but I assume they are the same.

**Comment by aldostools** [comment]
@LuanTeles I managed to get the following error with the PSP Launchers. It seems it's not related to the license. I fixed it creating a new user in XMB and launching the game from that user.
![image](https://github.com/aldostools/webMAN-MOD/assets/974897/365df15e-f0e4-4b68-8ccf-b6fb95551100)

The renew license issue could be related to the clock, missing act.dat or the user account needs activation or fake activation.

**Comment by LuanTeles** [comment]
> @LuanTeles I managed to get the following error with the PSP Launchers. It seems it's not related to the license. I fixed it creating a new user in XMB and launching the game from that user. ![image](https://private-user-images.githubusercontent.com/974897/311236790-365df15e-f0e4-4b68-8ccf-b6fb95551100.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MTk0MTMsIm5iZiI6MTcwOTkxOTExMywicGF0aCI6Ii85NzQ4OTcvMzExMjM2NzkwLTM2NWRmMTVlLWYwZTQtNGI2OC04Y2NmLWI2ZmI5NTU1MTEwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOFQxNzMxNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZmQ5ODg5YTlmYzk0ZDRkNDdhOTIxOWE0YjA5ZDk2ZWJkMWRmMzVlMjRiMDMwMDg0YWJlYmE4NTIwZDA2YTU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LbhoEMPATeX_cVSpPtpfI5evKUn76n9ubU920VlchfQ)
> 
> The renew license issue could be related to the clock, missing act.dat or the user account needs activation or fake activation.


I didn't have this issue; mine simply says that I need to go to the PS Store to renew its licenses.


BTW, yesterday I ran some tests. I launched a PSP game on Evilnat, and it created the RIF, and the launcher worked. Then I flashed HFW and HEN 3.2.2, and it worked just fine (because of the created rif). So, I deleted my RIF created by Cobra 8.4 to see if HEN could create one but it didn't and i got that screen again.

This test was done on 4.90, i couldn't test on 4.91 because the PS3 i installed the 4.91 HFW and HEN test 3.3.0 is with my cousin. (But it was not creating the rif too)

I'll ask esc0 for a build for 4.90 so i can test it on my main PS3, last time he updated me, he and joonie were hard coding the RAP for both ps2 and psp in the payload.

**Comment by LuanTeles** [comment]
See, this is the screen: (mine is modded, but you got the concept)

Hen payload is not creating the RIF for the launcher (At least the last version i tried (test 2) )
 
![image](https://github.com/aldostools/webMAN-MOD/assets/110236244/794ba709-aa00-41b3-a6f7-bb10aff484ff)

**Comment by aldostools** [comment]
There are 2 PS2 Launchers: one for minis and other for Remasters.

If I'm correct PS3HEN only creates the RIF for the one with the content ID: UP0001-PSPC66820_00-0000111122223333

I guess your issue could be solved easily including the RAP files in the HEN installation or installing this PKG.
https://github.com/aldostools/Resources/releases/download/Addons/install_ps2_psp_launchers_licenses.pkg

**Comment by LuanTeles** [comment]
****

> There are 2 PS2 Launchers: one for minis and other for Remasters.
> 
> If I'm correct PS3HEN only creates the RIF for the one with the content ID: UP0001-PSPC66820_00-0000111122223333
> 
> I guess your issue could be solved easily including the RAP files in the HEN installation or installing this PKG. https://github.com/aldostools/Resources/releases/download/Addons/install_ps2_psp_launchers_licenses.pkg


Yeap, that's the ContentID that i have, but HEN was not creating it. 

Thanks for the RAPs aldo, Esc0 was looking for it yesterday, i only sent him my rif as i couldn't convert it to RAP through Cobra, for an unknow reason.

Jason and Joonie are Hard coding the RAPs for it in the payload, let's see how it goes


![image](https://github.com/aldostools/webMAN-MOD/assets/110236244/346f3aab-bf5b-46c5-ab48-bec826a84ac5)

**Comment by aldostools** [comment]
Joonie is correct the RAP is not needed. Anyway I created the PKG for the people that want the RIF created.

The issue seems related to the account or system activation in PSN.

**Comment by alfredox123** [comment]
> There are 2 PS2 Launchers: one for minis and other for Remasters.
> 
> If I'm correct PS3HEN only creates the RIF for the one with the content ID: UP0001-PSPC66820_00-0000111122223333
> 
> I guess your issue could be solved easily including the RAP files in the HEN installation or installing this PKG. https://github.com/aldostools/Resources/releases/download/Addons/install_ps2_psp_launchers_licenses.pkg

This pkg works on 4.90 hfw and HEN 3.2.2? should i try without a risk of any kind?

**Comment by aldostools** [comment]
If your PSN account in activated, that PKG should work on HEN or CFW without any issue. It only creates the RAP files in /dev_hdd0/exdata for use by the payload when it needs them.

Anyway the next release of PS3HEN has this issue fixed. It will be released very soon.

**Comment by alfredox123** [comment]
ok then i wait, thank youu

**Comment by alfredox123** [comment]
Fixed on PS3hen 3.3.0 thanks!
