### ISSUE TITLE
Please help me fix this !

### ISSUE THREAD

**Issue by zakariaoussete** [aldostools/webMAN-MOD#971]
I installed the full version of webMAN_MOD now everytime i reboot my ps3 either soft or hard reboot the fan goes crazy how i can get out of webMAN_MOD i can't do that i tried everything !

**Comment by aldostools** [comment]
If your PS3 has custom firmware, turn off your console and enter to recovery menu holding the power button until you hear 2 beeps. Release the power button, connect the USB cable to your controller, press PS and  select 1. Restart the System.

When you enter to recovery menu the file boot_plugins.txt is deleted, preventing the load of VSH plugins.

Open a file manager like multiMAN or IRISMAN to delete the plugin /dev_hdd0/plugins/webftp_server.sprx

If your console has PS3HEN, create an empty file named boot_plugins.txt on the root directory of a pendrive or USB drive, connect the USB device to your console and enable HEN.

The empty boot_plugins.txt will prevent the load of VSH plugins when HEN is enabled. Remember to remove the file from the USB device when your issue is resolved.
