### ISSUE TITLE
White square shows up when login into PSN

### ISSUE THREAD

**Issue by Vimu0** [aldostools/webMAN-MOD#986]
Everytime when i turn on my PS3 and try to log into PSN, a white square appears and i can only back out to the XMB (Not logged into PSN)
![IMG_20231127_234403566_HDR](https://github.com/aldostools/webMAN-MOD/assets/52721796/877c85ae-6736-4461-bc10-07719f44378c)

**Comment by aldostools** [comment]
It looks like **npsignin_plugin.rco** is being mapped to non existing resource.

Try copying [npsignin_plugin.rco](https://github.com/aldostools/webMAN-MOD/raw/master/_Projects_/updater/pkgfiles/USRDIR/res/npsignin_plugin.rco) manually to /dev_hdd0/tmp/wm_res (use FTP or a File Manager)

**Comment by Vimu0** [comment]
Now the "PlayStation Network Disabled" screen shows up but after pressing R2 and Triangle like it says to do I'm still getting the exact same issue
![IMG_20231129_123512929](https://github.com/aldostools/webMAN-MOD/assets/52721796/b3debe52-9908-42ff-93bc-f8d9e1f339b9)

**Comment by aldostools** [comment]
Are you using HEN? As far as I know, the issue occurs because there is a bug in HEN unmapping paths.

If you delete /dev_hdd0/tmp/wm_res/npsignin_plugin.rco and update to the latest build of webMAN MOD, the issue should not happen because webMAN MOD not longer remaps that resource file.

The same solution applies for CFW 4.90 since that feature is already part of the Custom Firmare Tools menu.

Another possible cause is that the custom combo R2+TRIANGLE could be disabled in /setup.ps3

**Comment by Vimu0** [comment]
Yes i am, the troubleshooting steps that you recommended did not work, everything was working perfectly normal except hen, figured out that i had to reinstall the entire firmware because of hen thanks for the help though.

**Comment by aldostools** [comment]
I only use CFW, therefore I'm not very experienced with HEN.

I recommend you that ask in [PSX-PLACE forums](https://www.psx-place.com/forums) how other users solved your issue.

In the recent builds webMAN MOD does not install npsignin_plugin.rco anymore because this was a common issue reported by HEN users that I couldn't reproduce on CFW.
